### ISSUE TITLE
Support for abbreviations not implemented

### ISSUE THREAD

**Issue by fletcher** [fletcher/MultiMarkdown-6#1]
Abbreviation support is not available yet.  I'm not sure the best way to implement it, as it will need a slightly different approach than in MMD-5

**Comment by fletcher** [comment]
I'm not entirely dissatisfied with the way abbreviations work in MMD-5, however the algorithm to replace them will need to be modified.  There are two general options:

1. Read the document to find all abbreviation definitions, then scan the document for all uses of the abbreviation, and replace it with the appropriate syntax.  Advantage -- automatically identifies all uses of the abbreviation without user action.  Disadvantage -- requires scanning the entire document for each occurrence of each defined abbreviation.  In MMD-5, this meant that 10 abbreviations would require scanning almost every word of the document 10 times.  I've now worked on some code that could check for all 10 abbreviations in a single pass, but would still be a bit messy.

2. Require the author to "tag" each use of the abbreviation that they desire to be handled.  Each abbreviation would still only have to be defined once, but this would require more effort when writing or revising the document.  Advantage -- much more efficient, since abbreviations would be identified during the usual parse process, just like links and footnotes.  Disadvantage -- it becomes possible for an author to forget to take some uses of an abbreviation.

I welcome thoughts and input on this feature!

**Comment by nemesit** [comment]
I think the single pass scan beats option 2.

**Comment by fletcher** [comment]
As I think about this (and after re-implementing glossary support), I think that I will do a few things re: abbreviations:

1. The syntax will fall more in line with footnotes, citations, and now abbreviations -- something along the lines of the `[xfoo]` where `x` is some punctuation character.

2. The approach used for glossary items that requires tagging each use makes a lot of sense from a performance standpoint.  Comparing each word in the document to an abbreviation list is expensive.  And, because of the way MMD-6 is optimized for performance, it is a bit tricky.

3. What might make sense for automated identification of abbreviations within the text would be a separate (optional) stage that takes the identified list of abbreviations and automatically wraps each instance in the `[xfoo]` syntax before re-processing the document.

4. For those wanting "easy" -- give MMD a bit more time, and it will automatically identify each occurrence of abbreviations (and glossary terms?).  If you need performance -- then each instance should be marked in advance, and MMD will use it's normal fast approach.

**Comment by fletcher** [comment]
I think the new abbreviation syntax is better than the old one. There may still be room for some improvement.

See <https://github.com/fletcher/MultiMarkdown-6/wiki/Changes-from-MMD-5> for more information.

**Comment by mn4367** [comment]
The new syntax is nice but I'd like to vote for some sort of compatibility mode (command line switch, metadata key) which enables automatic identification of abbreviation and glossary terms. I'd happily accept the performance penalty.

**Comment by fletcher** [comment]
That was always on the list, and has been added this evening.  Abbreviations and glossary terms are now automatically identified.
