### ISSUE TITLE
User Guide is blank

### ISSUE THREAD

**Issue by stvhwrd** [fletcher/MultiMarkdown-6#100]
Every format of the [MMD6 user guide](https://fletcher.github.io/MultiMarkdown-6/) appears blank, with no meaningful content beyond the cover page, "what is Markdown", and a couple of headings.

![image](https://user-images.githubusercontent.com/4117011/33998586-d160a6c0-e09c-11e7-98c4-016bd997cfc7.png)

Contrasts with [MMD5 user guide](https://fletcher.github.io/MultiMarkdown-5/).

**Comment by fletcher** [comment]
Yup -- it's not updated.  You can use the v5 guide with the v6 Quick Start Guide for changes.
