### ISSUE TITLE
breaks latex compatibility with previous MMD versions

### ISSUE THREAD

**Issue by jlargentaye** [fletcher/MultiMarkdown-6#109]
As documented, the "latex input" directive has been deprecated in favor of `latex leader` and `latex begin`

While this is fine in and of itself, it breaks compatibility for documents that worked fine with MMD4/5, meaning that a given document cannot work on both MMD4/5 and MM6. This is a problem for situations with a mixed installation pool, like those using MacPorts that silently [upgraded from MMD4 to MMD6](https://github.com/macports/macports-ports/commit/2c9056110f4f897af5e11cb3aa0b5a664980d4a4).

A way around this would be for MMD6 to continue supporting the `latex input` directive, even if with a deprecation warning.

**Comment by fletcher** [comment]
Yup.

v6 is a "break backwards-compatibility" release in a few ways, this being one of them.  A couple of core pieces were restructured to improve overall functionality and flexibility, and this was a necessary consequence.

The `latex input` approach was a mistake, but one that was not easily recognized until down the road.

To work around, simply double up your metadata -- use the `latex input` for MMD 4/5 (it's ignored in v6), and use either the separate `leader/begin/etc` or the single `latex config` metadata for v6 (which will be ignored in v4/5).

But I won't be adding support for `latex input` back at this time.

**Comment by jlargentaye** [comment]
Thanks for the quick response!

I had actually tried the "use both metadata" method, and was spooked because MMD4 was adding

    \def\latexleader{mmd-memoir-header}

in the tex output. But indeed, on second thought these are harmless and the document does build fine.

Thanks for pointing me back on the right track!
