### ISSUE TITLE
Latex: '#' in a backtick section isn't properly escaped

### ISSUE THREAD

**Issue by jlargentaye** [fletcher/MultiMarkdown-6#110]
In multimarkdown 6.2.3, the following input markdown:

```
I don't #define myself that way

`but what if I #define this?`
```

Generates the following Latex output:

```
I don't \#define myself that way

\texttt{but what if I #define this?}
```

Note that the the # (hash) sign from the first line is backslash-escaped in the output, but not the one in the backticked line. The latter causes a latex error: `Illegal parameter number in definition of \reserved@a.`

FWIW, MMD4 properly handled this case

**Comment by ipetraka** [comment]
See also #108
