### ISSUE TITLE
Wrong path in markdown script

### ISSUE THREAD

**Issue by angelog0** [fletcher/MultiMarkdown-6#112]
I have installed the multimarkdown MacPorts package but the 'markdown' script fails when I try to use it with Emacs.

MacPorts installs the script and the binary (multimarkdown) in /opt/local/bin so

`[...]`
`# Be sure to include multimarkdown in our PATH`
`export PATH="$PWD:/usr/local/bin:$PATH"`

is insufficient to add the right PATH for multimarkdown : $PWD expands in the directory where the .md file, on which [multi]markdown is working on, lives and not where the script/binary lives.

See [MacPorts ticket #55805](https://trac.macports.org/ticket/55805)

**Comment by fletcher** [comment]
Actually, `$PWD` refers to the "current" directory, not the directory of the script or the file.

But if you don't install the shell scripts where they are expected, then setting the path to `/usr/local/bin` won't work.

Install them in the "proper" place, or modify the shell scripts as needed to accommodate your custom location.  Either should get you what you need.

**Comment by angelog0** [comment]
> Actually, $PWD refers to the "current" directory, not the directory of the script or the file.

I don't understand why you add the current directory to the PATH for searching multimarkdown binary and not the folder where the _script_ lives...

> Install them in the "proper" place, or modify the shell scripts as needed to accommodate your custom location. Either should get you what you need.

As you can see following the MacPorts ticket I suggested, there are at least two way to fix the issue, I have just installed the MacPorts package and flagged the issue to the interested people...
