### ISSUE TITLE
HTML Footer - metadata value is not included in output

### ISSUE THREAD

**Issue by geranyl** [fletcher/MultiMarkdown-6#114]
Maybe there's a new way to include html headers and footers but I haven't found the documentation for it.  

My experience is that having "HTML Header: " in metadata includes the value into the output file's header, but the "HTML Footer:" tag no longer adds content before the end body tag. Looks like in html.c you are printing out the header value, but the footer tag is ignored. I did manage to work around the issue by amending the mmd_end_complete_html function, but since I'm not exactly a C programmer, I figured I should just post this as an issue instead.

**Comment by fletcher** [comment]
v6 uses the `MMD Footer` metadata instead.  It's in the QuickStart guide under "Metadata".

**Comment by geranyl** [comment]
Thank you!
