### ISSUE TITLE
transcludebase is not used when path is enclosed by quotes

### ISSUE THREAD

**Issue by feekApp** [fletcher/MultiMarkdown-6#116]
Hi,

When the path for transcludebase is enclosed by quotes, the transcludebase is not used:

```
transcludebase: "/Users/Username/Dropbox/Sync/mmdStyles/"
```
is not working,

```
transcludebase: /Users/Username/Dropbox/Sync/mmdStyles/
```
works fine.

**Comment by fletcher** [comment]
So don't use quotes.

;)

**Comment by feekApp** [comment]
So true, not using quotes of course solve the issue :)

But, on the other hand, MMD5 did not have any problem with the quotes...

And an other problem is that the mmd meta-data (in my case) is generated by other code.

**Comment by fletcher** [comment]
Can you submit a working example where the transclude base metadata is in quotes?  It doesn't work for me in my test of v-5.

The intent was never that quotes would be automatically dropped.  So this would seem to be a bug in v5 that was fixed.

**Comment by feekApp** [comment]
Example of the MD-file that worked fine with MMD5, where `intro.md` is located in `/Users/Feek/Dropbox/Sync/mmdStyles/intro.md`

```
---
date: vrijdag 7 april 2017
title: Some Title
transcludebase: "/Users/Feek/Dropbox/Sync/mmdStyles"
viewport: width=device-width, initial-scale=1.0
css: https://www.mysite.com/md/style.css
xhtmlheader: <script type="text/javascript" src="https://www.mysite.com/md/highlight.js">
  </script> <script>hljs.initHighlightingOnLoad();</script>
client: The Client
number: 110105
subject: Some results
author: Feek
version: 10
---

# Some tekst

{{intro.md}}

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

```

**Comment by feekApp** [comment]
Sorry I cannot check the documents in MMD5 because I'am using a new installed macOS.

The only thing is why it possible works on my previous installation is because the meta data of the MMD-file is generated externally in Ruby

``` ruby

# Merge the Multi Markdown Meta data from two files

require 'yaml'

# First argument is the template file
# Assumed is the template has valid meta data (YAML)
templateMetaFile=ARGV[0]
documentMetaFile=ARGV[1]

# Read the template file and make a hash
theTemplateMeta = YAML.load_file(templateMetaFile)

# Read the document file and make a hash
theDocumentMeta = YAML.load_file(documentMetaFile)

if theDocumentMeta.class == Hash
  theDocumentMeta.each do |metaKey,value|
    theTemplateMeta[metaKey] = value
  end
end

# Return the merged Meta Data
puts theTemplateMeta.to_yaml
puts "---"

```

Possible in the previous version of  ruby YAML the links where not enclosed by quotes... Sorry cannot check that  :(

**Comment by fletcher** [comment]
It doesn't work for me in MMD 5 ( 5.4.0, or more precisely the latest development branch after 5.4.0).

Works fine when I remove the quotes.

Let me know if you are able to get it working in v5 as I'm curious, but I would need a better reason to handle quotes the way you suggest.

As an aside, that is the only metadata using quotes in your example, which seems strange.

To my knowledge, I have never used quoted metadata in any of my sample documents or test suites.

**Comment by feekApp** [comment]
Your right, that's the only meta-data that's quoted. As I said the meta-data is generated by the ruby code. In the original (to be merged) file, the meta data is unquoted. But the ruby YAML extension seems to quote file paths starting with a `/`

**Comment by feekApp** [comment]
Hi, I found a bootable backup disk of my previous system.....

The issue is caused by the YAML export via the ruby script. On my previous system, the meta data with the `transcludebase` folder url is generated without quotes.

**Comment by fletcher** [comment]
Glad you were able to track it down!
