### ISSUE TITLE
Block level HTML paragraphs, list items and MMD parsing within them

### ISSUE THREAD

**Issue by ghost** [fletcher/MultiMarkdown-6#117]
In accordance with the new system for processing text within HTML block level elements, there appears to be a some blind spots in how that is done. Here is one example that could be done in MMD5 with the --process-html flag:

```
<p class="something">Some *text* here.</p>
```

In MMD6, the idea seems to be that we should do the following:

```
<p class="something">

Some *text* here.

</p>
```

For one thing, this would produce suboptimal HTML from a human-readability standpoint, but that aside, the result of this in 6.3 is invalid HTML:

```
<p class="something">

<p>Some <em>text</em> here.</p>

</p>
```

I should think that any block level element (`<p>`, `<li>`, etc.) should be capable of this treatment. Ideally though, it would be nice to see a return of that --process-html flag. The lack of that means adjusting everything around the blank line rule, which as mentioned may not always be the best choice if the idea is to produce HTML humans might work with.

**Comment by fletcher** [comment]
This is a change, but it comes about for a couple of reasons:

1. Creating a fast parser requires a few changes compared to prior versions of MMD.  A PEG-based parser allows a huge amount of flexibility, but is generally slower, and can be *much* slower in some circumstances.  Creating an HTML parser (of sorts) inside the Markdown parser is one piece that is quite expensive, which does require a different approach to parsing MMD inside HTML.

2. In designing MMD-6, parsing inside HTML was a tricky spot.  The approach I was looking at started to look very similar to CommonMark, and in this case it made sense to be compatible.  CommonMark doesn't get everything right, but it gets many things right.  In regards to handling HTML, MMD-6 is generally compatible with CommonMark, and in this instance I get the same results for both, including a few variations as included below.


	# Block

	<p class="something">

	Some *text* here.

	</p>

	<p class="something">
	Some *text* here.
	</p>

	<p>
	Some *text* here.
	</p>

	<p>

	Some *text* here.

	</p>


	# Span

	<p class="something">Some *text* here.</p>

	<p>Some *text* here.</p>

I am not opposed to considering changes, but in this instance I would be inclined to include CommonMark compatibility as a factor.  

I'm also not entirely convinced that this particular example is a great example.  I would instead propose the following model:

	<div class="something">

	Some *text* here.

	</div>
