### ISSUE TITLE
Setting linespread to 1 for CriticMarkup margin notes in LaTeX

### ISSUE THREAD

**Issue by ipetraka** [fletcher/MultiMarkdown-6#120]
While not a problem with most of the provided LaTeX boilerplate files, when using the Manuscript set, the result for margin notes is a bit awkward in that they inherit the double-spaced formatting from the body text. According to the Manscript documentation, the command used to ensure the title page is single-spaced is `\singlespacing`. However I ran into undefined command errors when trying to insert that into the `\cmnote` command you define.

I had better luck with this:

```latex
\newcommandx{\cmnote}[2][1=]{\linespread{1.0}\todo[linecolor=red,backgroundcolor=red!25,bordercolor=red,#1]{#2}}
```

I've tested that in a few different places within some sample manuscript output, and it seems to have no adverse effects. I'm not sure if that would be a good command to use in all cases however, so it might be the right approach is to have mmd6-manuscript-packages.tex input a different criticmarkup include, made just for it (or any other future boilerplates that use non-standard line spacing models.

**Comment by ipetraka** [comment]
Ah, correction. I see upon opening the .sty that this in fact something you've put together yourself, rather than using the old Manuscript document class. That explains the "missing" command.

**Comment by fletcher** [comment]
I'll take a look at the problem and your solution next week and can look at incorporating it into the master repo.

Thanks for pointing this out!
