### ISSUE TITLE
CriticMarkup LaTeX output uses \sout and \underline

### ISSUE THREAD

**Issue by ipetraka** [fletcher/MultiMarkdown-6#121]
Since you are using the *soul* package, it would be a better idea to use its `\ul{...}` command for addition marking instead of `\underline{...}`, as the latter does not flow text well, putting the underlined text into a float. Additionally you are using the `\sout{...}` command, which doesn't work with *soul*, the `\st{...}` command should be used instead.

**Comment by fletcher** [comment]
Do you have a good example where things are broken?

**Comment by ipetraka** [comment]
It looks like the `\sout` problem is okay; I was using a slightly modified mmd6-memoir-packages file that lacked the *ulem* package. The underlining issue can be seen with the following example. Note the `\ul` command produces a better result across multiple lines:

```latex
\input{mmd6-article-leader}
\def\mytitle{Test}
\input{mmd6-article-begin}

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis \underline{nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur}. Excepteur sint \sout{occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit }anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis \ul{nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur}. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

\input{mmd6-article-footer}
\end{document}
```

**Comment by fletcher** [comment]
Will stick with default `\underline` since not everyone uses `soul`, but will swap the two when soul is activated.

**Comment by ipetraka** [comment]
Sounds like a good solution to me.
