### ISSUE TITLE
'%' in a backtick section isn't properly escaped for Latex output

### ISSUE THREAD

**Issue by jlargentaye** [fletcher/MultiMarkdown-6#123]
In multimarkdown 6.3.2, the following input markdown:

```
This is a %

`use ctrl-b %`
```

Generates the following Latex output:

```
This is a \%

\texttt{use ctrl-b %}
```

Note that the the % (percent) sign from the first line is backslash-escaped in the output, but not the one in the backticked line. In Latex, the % is used to start a comment until the end of the line, and causes a latex error: `! File ended while scanning use of \texttt .`

**Comment by jlargentaye** [comment]
Also % signs that may show up in URLs

**Comment by fletcher** [comment]
Thanks!

Pushed update to `develop` branch with a fix.
