### ISSUE TITLE
Trailing #s in headings not discarded

### ISSUE THREAD

**Issue by isg-software** [fletcher/MultiMarkdown-6#125]
Formerly, MMD complied with markdown syntax for headings with trailing "number signs":

MD source: `### Heading (3) ###`
should be compiled to: `<h3>Heading (3)</h3>`
but is now actually: `<h3>Heading (3) ###</h3>`

**Comment by ipetraka** [comment]
That should still be working the same way, I primarily only use that format for headings as I prefer the visbility. I'd check your syntax around the heading---for example if I leave extraneous whitespace after the closing hashes, I get the result you do.

**Comment by isg-software** [comment]
Ah, tanks for that hint. I'd forgotten that my self-written perl pre-processor appends auto-generated IDs to the heading lines, resulting in something like: `### Heading ### [ID]`
And this then results in `<h3 id="ID">Heading ### </h3>`.

The same without space: `### Heading ###[ID]` becomes `<h3 id="ID">Heading ###</h3>`.

I'm actually not sure if this is intended behavior or a bug (that's why I leave this thread open). But I can live with that, my pre-processor might simply drop the hashes on its own.

**Comment by fletcher** [comment]
It sounds like a bug, but in your software, not mine.  ;)
