### ISSUE TITLE
Cite Keys Lowercase in LaTeX

### ISSUE THREAD

**Issue by mrkwnzl** [fletcher/MultiMarkdown-6#127]
Hello,

I noticed that MMD6 transforms all my cite keys to lowercase, which breaks compatibility with my BibTeX library, as my cite keys are all capitalized. For example:

 MMD syntax:

`[10][#Author_2018]`

In LaTeX with MMD5:

`~\citep{10}{Author_2018}`

In LaTeX with MMD6:

`~\citep{10}{author_2018}`

Unfortunately, BibTeX is case-sensitive.

Is this an intentional change or a bug?

Thanks a lot!

**Comment by fletcher** [comment]
Did you use BibTeX in MMD for this document?  If you don't configure `bibtex` metadata, MMD creates inline citations which will convert to lowercase (standardized) keys.

When I use BibTeX properly, the cite keys remain in the original case and work properly (see the BibTeX test for an example.)

Also, just to be sure, are you using a recent version of MMD 6?

**Comment by mrkwnzl** [comment]
I’m actually using Scrivener 3.0.3, so I’m not sure what version is actually used. I hope it‘s the most recent, but I haven’t found any documentation about that. But configuring the Metadata actually worked. Thanks a lot!

**Comment by fletcher** [comment]
Glad that did it!
