### ISSUE TITLE
Short caption not working

### ISSUE THREAD

**Issue by tux-mind** [fletcher/MultiMarkdown-6#130]
Hi, I found that short caption is not working as documented [here](https://rawgit.com/fletcher/human-markdown-reference/master/index.html) for latex.

The title is not used in the list of figures. After a closer look, I saw that you are not using the title attribute of the image when generating the caption token.

All the best, tux-mind.

**Comment by fletcher** [comment]
Can you give me an example figure that isn’t working for you?

F-
