### ISSUE TITLE
Math-mode triggered for inline raw

### ISSUE THREAD

**Issue by sorbits** [fletcher/MultiMarkdown-6#134]
I was surprised to find the following transformation happening:

On the left is input and right shows output:

    `${foo:-${bar}}`   =>   <p><code>\({foo:-\){bar}}</code></p>

Using v6.3.2 installed via homebrew.

If I provide `--compatibility` then the desired output is generated.

I assume that `$…$` triggers math-mode, but I am not sure this should happen for inline raw, as that disables all other special characters.

**Comment by fletcher** [comment]
Thanks -- this was an oversight in fixing something similar for the other math delimiters.

Fixed in development branch.
