### ISSUE TITLE
Non-first blank lines in HTML blocks enable markdown mode

### ISSUE THREAD

**Issue by sorbits** [fletcher/MultiMarkdown-6#135]
I understand that an initial blank line in an HTML block enables markdown mode, but I would not expect later lines to do this, for example with this input:

    # Hello world

    <div>
        <p>First paragraph</p>

        <p>Second paragraph</p>
    </div>

I get the following output:

    <h1 id="helloworld">Hello world</h1>

    <div>
        <p>First paragraph</p>

    <pre><code>&lt;p&gt;Second paragraph&lt;/p&gt;
    </code></pre>

    </div>

If the rule is that *any* blank line in HTML blocks enable markdown mode (for the remaining content), it means that we cannot visually group elements, which would be a loss for readability.

Using v6.3.2 installed via homebrew.

Using `--compatibility` does not change the above behavior.

**Comment by fletcher** [comment]
HTML is handled at the "block" level, and blank lines (under most circumstances) start new blocks.

This behavior is different in MMD v6 as compared to prior versions.  v2 was basically a modified version of `Markdown.pl` and used the same regex parser which was flexible but insanely slow and prone to terrible edge case behavior.  v3-v5 used a PEG-based parser which was fast and flexible, but still prone to some edge case slowdowns with excessive backtracking.  v6 is **much** faster, and is more "consistent", and runs without backtracking.  

Those benefits do come at the cost of less flexibility under certain circumstances -- primarily that MMD can't "look ahead" an unspecified number of lines to determine how to interpret the current line:

* Fenced code blocks can't verify a closing fence "in the future" before deciding to open the block, so once started the run until closed or document ends
* HTML (at the block level) can't be verified for validity "chunked" by looking ahead for the closing tag.

Which means that each block is treated independently and blank lines define new blocks.

This behavior is consistent with that used by CommonMark, and I get the same results for your test situation with MMD as with CommonMark (using Babelmark 2 for testing.)  CommonMark doesn't get everything right, but it does get a lot of things right.  And given that a regex-based parser is a "no go" from a performance perspective, I arrived at virtually the same result for MMD that they arrived at for CommonMark, so this was an instance where compatibility between the two makes sense.


As an aside, `compatibility` mode changes the available features in MMD but does not change the underlying parser.  This behavior is a fundamental property of the parser, so it cannot be changed.
