### ISSUE TITLE
New release after 6.3.2?

### ISSUE THREAD

**Issue by jlargentaye** [fletcher/MultiMarkdown-6#137]
It's been a while since the last release, 6.3.2 on March 28th, and there have been a few bugfixes that I care about that landed in the "develop" branch.

How can I help for a new release?

**Comment by fletcher** [comment]
I don't have a fixed timetable for "official" releases.  I still have a couple of things I would like to work on, so I'm not quite ready to do it now.

But that's also why I push to the develop branch -- anyone can compile from develop at any time to take advantage of the most recent bug fixes if they need them.

Alternatively, if you know of a good, free, preferably open-source, service that will automatically create installers for multiple platforms from tagged github release commits, I'm open to exploring it.  Obviously the time consuming part is not moving to the master branch, it's creating the installers and uploading them to github.
