### ISSUE TITLE
pound in code block causes spaces to disappear

### ISSUE THREAD

**Issue by cptMikky** [fletcher/MultiMarkdown-6#140]
In mutlilne code when the first character on a line is a pound (`#`) followed by spaces, then all the spaces are deleted in resulting html:

    ```
    text
    # another text
    ```

will yield:
```html
<pre><code>text
#another text
</code></pre>
```

while it should yield:
```html
<pre><code>text
# another text
</code></pre>
```

**Comment by fletcher** [comment]
Use the develop branch -- it's already been fixed.  It will be included in the next release version as well.
