### ISSUE TITLE
Build fails because curl library is not linked

### ISSUE THREAD

**Issue by ryandesign** [fletcher/MultiMarkdown-6#145]
Building multimarkdown 6.4.0 on macOS fails:

```
Undefined symbols for architecture x86_64:
  "_curl_easy_init", referenced from:
      _epub_create in epub.c.o
      _opendocument_core_file_create in opendocument.c.o
      _textbundle_create in textbundle.c.o
  "_curl_easy_perform", referenced from:
      _epub_create in epub.c.o
      _opendocument_core_file_create in opendocument.c.o
      _textbundle_create in textbundle.c.o
  "_curl_easy_setopt", referenced from:
      _epub_create in epub.c.o
      _opendocument_core_file_create in opendocument.c.o
      _textbundle_create in textbundle.c.o
  "_curl_global_init", referenced from:
      _epub_create in epub.c.o
      _opendocument_core_file_create in opendocument.c.o
      _textbundle_create in textbundle.c.o
```

The solution is to add `-lcurl` to `LDFLAGS`, but I don't know what the correct way to do that in CMakeLists.txt is.

**Comment by fletcher** [comment]
How are you building? Works fine for me.

**Comment by ryandesign** [comment]
> How are you building?

With MacPorts. We are setting the `-DSHAREDBUILD=1` flag for cmake. It appears that without that, it adds `-lcurl`.

**Comment by ryandesign** [comment]
Well, the problem still occurs if I build manually, outside of MacPorts.

**Comment by fletcher** [comment]
I suspect it's something with the way your machine is configured??  I added the libcurl stuff around a year ago and build MMD on several macs several times a week on average without any trouble.  I have to disable libcurl when building for iOS because libcurl is not built-in there, and I haven't gotten around to compiling my own iOS version.

Perhaps try a new macOS user so that you can reset any user-level environment changes?  Obviously any system-level stuff will still be there.

And I assume you are doing:

    make
    cd build
    make

??


PS>  Headed to bed, but will pick this up again tomorrow.

**Comment by ryandesign** [comment]
There's probably nothing wrong with my macOS user, since the problem was originally found and worked around by a previous MacPorts developer when he [updated our multimarkdown port from 4.5 to 6.2.3](https://github.com/macports/macports-ports/commit/2c9056110f4f897af5e11cb3aa0b5a664980d4a4) earlier this year. It looks like he didn't report that or the several other patches he made to the port to you, which is why I'm reporting them to you now.

If you use `-DSHAREDBUILD=1`, it should be easy to reproduce the problem. [Here](https://gist.github.com/ryandesign/932833b77bdbc18154bc2535f3f8d113) is a console transcript...

We don't run `make; cd build; make`, but I see now in the readme that you say we should do this. I'm was confused about this, until I realized that you have a custom Makefile in the root directory which is set up to run `cmake` in the build directory. In MacPorts, we don't use that Makefile, because we want to run `cmake` with a wide range of options that your Makefile doesn't use. We also make our own arrangements for out-of-source builds.

I have now also tried your method, and it fails with the same undefined symbols, when I use `make shared; cd build; make`.

**Comment by ryandesign** [comment]
> I misread your earlier message as you had to use `-DSHAREDBUILD=1` to try and fix the problem. But you only have a problem when you use it?

Yes.

> Why are you using the sharedbuild option? That was added for certain *nix builds (I don't recall offhand which one). Just build it normally.

I assumed that there was some value in doing so, that there were other programs out there that would want to use this library. But if it's only an internal library used by multimarkdown, then I agree. Building normally works.
