### ISSUE TITLE
CMakeLists.txt is confused about whether C99 or C11 is used

### ISSUE THREAD

**Issue by ryandesign** [fletcher/MultiMarkdown-6#149]
CMakeLists.txt says both:

```
	add_definitions("-std=c99")
```

and:

```
# Use C11
set_property(TARGET libMultiMarkdown PROPERTY C_STANDARD 11)
set_property(TARGET multimarkdown PROPERTY C_STANDARD 11)
```

Which standard are you using?

**Comment by fletcher** [comment]
Was 99, but had to change to 11 for some reason (don't remember what at this point, and probably doesn't matter.)  I'll test removing the old c99 reference.

**Comment by fletcher** [comment]
I *think* the C11 was overriding the C99 anyway, but I have deleted it. 

Thanks!
