### ISSUE TITLE
Pointer dereferencing missing

### ISSUE THREAD

**Issue by derestle-htwg** [fletcher/MultiMarkdown-6#152]
https://github.com/fletcher/MultiMarkdown-6/blob/95bc39cc5e5f54a7ca4f1098536daf6a8454e11f/Sources/libMultiMarkdown/file.c#L237

test is a pointer to char but is not dereferenced. So the comparsion it is useless.

same mistake in writer.c:106

**Comment by fletcher** [comment]
Good catch -- it doesn't hurt anything, but could affect performance slightly with long copies.
