### ISSUE TITLE
Any way to suppress the figcaption generation for images without making them inline?

### ISSUE THREAD

**Issue by abartov** [fletcher/MultiMarkdown-6#153]
My use case is I want the images to be block-level, on their own in a paragraph, and I *also* want to provide an alt-text, for accessibility, but I *don't* want to display the alt text as a caption by default.

**Comment by fletcher** [comment]
You can change MMD's behaviour however you like by modifying the source.

Short of that you, could add something invisible after the image to prevent it from becoming a figure, such as appending `&nbsp;` or a linebreak using `\<newline>`.

**Comment by abartov** [comment]
Got it, thanks!
