### ISSUE TITLE
Line breaks don't work in headers

### ISSUE THREAD

**Issue by larrykollar** [fletcher/MultiMarkdown-6#155]
Tested with MultiMarkdown 6.4.0, MacOSX High Sierra

Example input file:

```markdown
---
title: test
---

# This is a test
If this had been an actual document...

## Chapter 2\
Heading with line break

...it would have had some content.
```

The output is:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
        <meta charset="utf-8"/>
        <title>test</title>
</head>
<body>

<h1 id="thisisatest">This is a test</h1>

<p>If this had been an actual document&#8230;</p>

<h2 id="chapter2">Chapter 2</h2>

<p>Heading with line break</p>

<p>&#8230;it would have had some content.</p>

</body>
</html>
```

What should be the second line of the heading becomes a paragraph. Adding a `##` to the second line just creates another heading.

**Comment by fletcher** [comment]
Correct.  Headers are a single line.

MMD-6 does support multiple line headers when using the Setext format for H1 and H2, as does CommonMark.   (This is *not* standard Markdown and is not supported in other Markdown parsers.)
