### ISSUE TITLE
Provide multiple LaTeX begin lines or values (feature request)

### ISSUE THREAD

**Issue by ekleinod** [fletcher/MultiMarkdown-6#158]
It would be great to allow multiple `latex begin` metadata keys or maybe a list of files for one key.

Reasoning: I use multimarkdown for many files with different LaTeX packages, e.g. changes, longtable, tabu, etc. At the moment with MMD 5 I use one LaTeX input file that contains the `usepackage`, properly named `mmd-changes` etc. Thus I can combine the packages freely:

  `latex input: mmd-changes`
  `latex input: mmd-longtable`

etc.

With the new approach I would have to provide a mmd file for each combination, i.e. `mmd-changes`, `mmd-longtable`, `mmd-changes-longtable`, etc. This becomes very tiresome and hard to maintain (I too have files which use the same packages. with different options - naming will become a catastrophy).

I see two possible solutions: multiple `latex begin` which, as I understand, would be the only key to appear multiple times, so this would not be the preferred solution.

The other solution would be to allow multiple files per `begin` (maybe for consistency `leader` and `footer` too):

  `latex begin mmd-changes, mmd-longtable`

This would be very elegant in my opinion.

**Comment by fletcher** [comment]
Why not use `latex header` instead?  That's what it's there for:

	latex config: article
	latex header:  \input{mmd-changes} \
		\input{mmd-longtable}

	## Hello ##

	Goodbye

This results in:

	\input{mmd6-article-leader}
	\input{mmd-changes} 
	\input{mmd-longtable}
	\input{mmd6-article-begin}

	\chapter{Hello}
	\label{hello}

	Goodbye

	\input{mmd6-article-footer}
	\end{document}


This seems more elegant....  Plus, it already exists....  ;)

(It does require that your custom commands fit between the `leader` and `begin` files, but this should be the case for things like this.)

**Comment by ekleinod** [comment]
Yes, you are right (it has to look for you as if I never read the documentation, which I did, sorry).

Thanks for your response.

**Comment by fletcher** [comment]
Not a bit -- MMD is by no means "turing complete", but it is actually pretty flexible and there is often more than one way to accomplish a goal.  Glad this worked for you!!
