### ISSUE TITLE
v6.4.0 mmd2pdf fails

### ISSUE THREAD

**Issue by webradio** [fletcher/MultiMarkdown-6#159]
mmd2pdf fails in my case.

Small text file is called tryme.mmd
````
# Short Test
This is the shortest test ever.
````

The command I try is
````
multimarkdown --version
mmd2pdf tryme.mmd
````
It returns `MultiMarkdown 6 v6.4.0`

tryme.tex contains:
````
\part{Short Test}
\label{shorttest}

This is the shortest test ever.
````

tryme.log contains:
````
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=latex 2018.11.10)  10 NOV 2018 15:48
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**tryme.tex
(./tryme.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 3 language(s) loaded.
! Undefined control sequence.
l.1 \part
         {Short Test}
? 
! Interruption.
<to be read again> 
                   {
l.1 \part{
          Short Test}
? 

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 \part{S
           hort Test}
?
````

**Comment by fletcher** [comment]
The test file you created is not complete for processing with LaTeX. 

You would need ‘latex config’ metadata, or the equivalent. Which also means installation of a working latex installation and the MultiMarkdown latex support files. 

The MultiMarkdown 6 updates are described here:

https://fletcher.github.io/MultiMarkdown-6/syntax/metadata.html#latexconfig

For more general latex usage I would use google - there is a lot of information in various places.
