### ISSUE TITLE
Create OS X Installer

### ISSUE THREAD

**Issue by fletcher** [fletcher/MultiMarkdown-6#16]

**Comment by nemesit** [comment]
please avoid pkg or other installers, make a brew formula and maybe a dmg where users can drag and drop the files themselves (maybe to aliases) and a readme. Installers are really not worth it with all their annoying downsides.

**Comment by fletcher** [comment]
MMD 5 is already available in homebrew, and I plan on adding MMD-6 as well.

Drag/drop is probably not a great option for commands that need to be installed in system libraries -- most users do not understand what folders like `/usr/local/bin` are.  Drag drop is more reasonable for OS X applications.

Of course, more experienced users can do whatever they like.
