### ISSUE TITLE
My antivirus is considering MultiMarkdown as a virus

### ISSUE THREAD

**Issue by daacosta** [fletcher/MultiMarkdown-6#160]
Panda Antivirus is falsely detecting Multimarkdown as a virus. :(

**Comment by fletcher** [comment]
I guess that is better than your antivirus software missing actual viruses, but still doesn't inspire confidence.

Of course, the fact that they market themselves as providing antivirus software for iOS makes me question the legitimacy of this product.

**Comment by daacosta** [comment]
I have reported the issue at Panda AV...
