### ISSUE TITLE
can you add documentation to use mmd in gitlab-ci?

### ISSUE THREAD

**Issue by larrycai** [fletcher/MultiMarkdown-6#161]
will be good if you can provide sample how to use it in gitlab-ci in simple way? 

- do u have binary release somewhere to download directly
- do u have docker image which can be used there

Rgs, Larry

**Comment by fletcher** [comment]
I don't use gitlab-ci, so I can't offer any specific input.

If you're using it in a CI test environment, then you wouldn't want a binary -- you would want it to be compiled and built on demand to allow for live testing.  

I do this with Travis, so you can examine the .travis.yaml configuration file to see how that works.
