### ISSUE TITLE
possible bug: latex footnote for special character "%"

### ISSUE THREAD

**Issue by larrycai** [fletcher/MultiMarkdown-6#163]
I use multimarkdown-6/ubuntu18.04, and noticed error for footnote, real example is https://tex.stackexchange.com/questions/469347

For testing, I use `test.md`

<pre>
# sample
link [abc](http://https://www.google.com/search?q=%3B+url)
</pre>

And I use `multimarkdown -t latex test.md` to generate latex code and put into latex like below

<pre>
\documentclass{article}
\usepackage{hyperref}
\begin{document}

\part{sample}
\label{sample}

link \href{http://https://www.google.com/search?q=%3B+url}{abc}\footnote{\href{http://https://www.google.com/search?q=%3B+url}{http:\slash \slash https:\slash \slash www.google.com\slash search?q=\%3B+url}}

\end{document}
</pre>

Then it reports error when I compile

<pre>
File ended while scanning use of \@footnotetext.
</pre>

It can be manually fixed by adding extra `\` before `%3B`

<pre>
.. {abc}\footnote{\href{http://https://www.google.com/search?q=\%3B+url}...
</pre>

**Comment by fletcher** [comment]
The LaTeX generated by MMD for some features does rely on a few common packages that it appears you have not enabled.

When used properly, your example works for me:

	latexconfig: article

	## sample 

	link [abc](http://https://www.google.com/search?q=%3B+url)

The `latexconfig: article` configures LaTeX (via MMD) to use a group of LaTeX "configuration files", such as `mmd6-article-begin.tex`, etc.  These are included in this repository, but do need to be installed on your system.  The resulting LaTeX file is:

	\input{mmd6-article-leader}
	\input{mmd6-article-begin}

	\chapter{sample}
	\label{sample}

	link \href{http://https://www.google.com/search?q=%3B+url}{abc}\footnote{\href{http://https://www.google.com/search?q=%3B+url}{http:\slash \slash https:\slash \slash www.google.com\slash search?q=\%3B+url}}

	\input{mmd6-article-footer}
	\end{document}


Alternatively, you can manually include the required packages, but you'll have to figure out which one is required for your desired footnote.
