### ISSUE TITLE
[bug] fenced code block translation into HTML code is wrong, cannot be highlighted.

### ISSUE THREAD

**Issue by linpengcheng** [fletcher/MultiMarkdown-6#164]
fenced code block translation error, cannot be highlighted (prism.js or  highlight.js).
prism.js is simpler and more popular.

<pre><code>
```clojure
(def x 5)
```
</code></pre>
was incorrectly translated into: 
```html
<pre><code class="clojure">
(def x 5)
</code></pre>
```
Correct should be translated as:
```html
<pre><code class="language-clojure">
(def x 5)
</code></pre>
```
If this is the case, you can highlight it with the following code
```markdown
    <link rel="stylesheet" href="/path-to/prismjs/prism.css">
    <script src="/path-to/prismjs/prism.js"></script>
    ```clojure
    (def x 5)
    ```
```

**Comment by fletcher** [comment]
I'm not sure what you mean by "incorrectly translated"....  You typed `clojure`.  MMD outputs `clojure`.  There is no translation.  If you want `language-clojure` then type `language-clojure`.  You can use whatever highlighting library you prefer.
