### ISSUE TITLE
Bug with italic, non breaking space and hyphen

### ISSUE THREAD

**Issue by jackygag** [fletcher/MultiMarkdown-6#166]
To reproduce this issue with italic you will need something like this:
*ITALIC_WORD_WITH_HYPHEN*+non-breaking_space+WORD+non-breaking_space+ *ITALIC_WORD*

MMD example: I love \*Viet-Nam\* and \*Peru\*!  
(same example, but showing position of non-breaking spaces : I love *Viet-Nam*&nbsp;and&nbsp;*Peru*!)

Result: the word "and" is in italic with mmd 6.4.0…
<img width="205" alt="MMD 6 4 result" src="https://user-images.githubusercontent.com/48492349/54226707-bc096a80-44d4-11e9-832d-f6233fe3369c.png">

**Comment by fletcher** [comment]
I can't reproduce this, either in development branch or 6.4.0 in master.

Can you attach a file with the raw MMD text you are attempting to process?  It's not clear what your original source looks like (`foo\ and\ bar`, `foo&nbsp;and&nbsp;bar`, etc.).

**Comment by jackygag** [comment]
Here the file :
[bug.md.zip](https://github.com/fletcher/MultiMarkdown-6/files/2958591/bug.md.zip)

**Comment by fletcher** [comment]
Use MMD for non-breaking spaces, e.g. `foo\ bar`.

As far as MMD is concerned, you're typing `*Viet-Nam*XandX*Peru*!` which leads to results different than you desire since there is no ASCII whitespace or punctuation inside the word to break it up.
