### ISSUE TITLE
Swift libMultimarkDown.framework and footnotes

### ISSUE THREAD

**Issue by laurent-humbert** [fletcher/MultiMarkdown-6#168]
I built and installed the libMultimarkDown.framework in my Swift Xcode 10.2.1 project, I managed to get things to work and translate a markdown to html, but only for simple links.

I tried footnotes, and also markdown="1", but they are ignored.

I simply copied the code from main.swift, is there anything else I forgot ?

Thanks

**Comment by laurent-humbert** [comment]
I got things to work, added the EXT_NOTES parameter and also used the new formatting for inline html

**Comment by fletcher** [comment]
Correct -- The `libMultiMarkdown.h` header contains the various constants that you need to use the library and control which features you want.

It also includes the IMPORTANT notice at the top about `token.h`.

Glad it's working for you!
