### ISSUE TITLE
Memory leak when using mmd_critic_markup_accept()

### ISSUE THREAD

**Issue by aschmidjr** [fletcher/MultiMarkdown-6#172]
While integrating MMD into an iOS project I noticed that a call to

    mmd_critic_markup_accept(buffer);

causes a memory leak. I actually think that the issue lies in 

    token * mmd_critic_tokenize_string(...)

because `trie * ac` is conditionally released, which I think is incorrect. It can easily be fixed by changing 

     if (m) {
         ....
        match_free(m);
        trie_free(ac);
    }

to

    if (m) {
         ....
        match_free(m);
    }
    trie_free(ac);

Thank you!
Alfons

**Comment by fletcher** [comment]
Thanks for pointing this out!!
