### ISSUE TITLE
Binaries are missing in the release assets of 6.5.0

### ISSUE THREAD

**Issue by alphatan** [fletcher/MultiMarkdown-6#178]
The binaries for Windows and Mac are missing in the release of 6.5.0.

Could them be found somewhere ?

Thanks.

**Comment by fletcher** [comment]
I'll have to compile them when I get a chance.

**Comment by alphatan** [comment]
Waiting..... eagerly.....

**Comment by dgreen** [comment]
I think the Mac binaries may still be in process.

**Comment by fletcher** [comment]
The old macOS workflow no longer worked, so had to research updates.  New approach now working.
