### ISSUE TITLE
Beamer mode does not include footer

### ISSUE THREAD

**Issue by krontzo** [fletcher/MultiMarkdown-6#185]
MM6 versions: 6.5.2 and 6.4.0
OS: Ubuntu 18.04.4

While using `latex mode: beamer` from metadata or command line `-t beamer`, the footer is not included; even if `latex config: beamer` is defined.

Result:
```latex
\end{frame}

\mode<all>
\end{document}\mode*
```

Expected:
```latex
\end{frame}

\mode<all>
\input{mmd6-beamer-footer}

\end{document}\mode*
```

**Comment by fletcher** [comment]
Thanks!
