### ISSUE TITLE
Pb with header IDs

### ISSUE THREAD

**Issue by laurent-humbert** [fletcher/MultiMarkdown-6#186]
Hi there,

Possibly a dumb question, but when I convert

`## Some Text {#1591276835}`

to html, I get

`<h2 id="sometext1591276835\">Some text {#1591276835}</h2>`

Is there any option to have  `{#1591276835}` removed, and have the result look like

`<h2 id="1591276835\">Some text</h2>`

?

Thanks;

I'm using the latest version of MultiMarkdown-6 from within Xcode

**Comment by fletcher** [comment]
`{#foo}` like that is not Markdown.

To override the default `id`, you can use `[Manual ID]`, as described here -- <https://fletcher.github.io/MultiMarkdown-6/syntax/cross-references.html>

**Comment by laurent-humbert** [comment]
Thanks!

**Comment by fletcher** [comment]
You’re welcome!
