### ISSUE TITLE
"latex input:" ignored in v6.5.2

### ISSUE THREAD

**Issue by jmbhill** [fletcher/MultiMarkdown-6#189]
I've been thinking all day that I had something misconfigured, but it looks like I've found an issue with v6.5.2.
The "latex input:" metadata command appears to be ignored, but the "latex footer" appears to work. Below I am using the sample.txt file from the github gallery.

```
benson@Bensons-MBP> multimarkdown --v | grep 6
MultiMarkdown 6 v6.5.2
Copyright © 2016 - 2020 Fletcher T. Penney.
    The `MultiMarkdown 6` project is released under the MIT License..
        Copyright (c) 2005-2016, Troy D. Hanson
 benson@Bensons-MBP> multimarkdown -t latex sample.txt | grep input
\input{mmd-memoir-footer}
```
But when I try the same thing with v5.4.0 I get this
```
benson@Bensons-MBP> multimarkdown --v | grep 5
MultiMarkdown version 5.4.0
 benson@Bensons-MBP> multimarkdown -t latex sample.txt | grep input
\input{mmd-article-header}
\input{mmd-natbib-plain}
\input{mmd-article-begin-doc}
\input{mmd-memoir-footer}
```

**Comment by fletcher** [comment]
LaTeX configuration is different in v6.  The metadata keys are described in the documentation:

https://fletcher.github.io/MultiMarkdown-6/syntax/metadata.html#latexconfig
