### ISSUE TITLE
Release ubuntu binary

### ISSUE THREAD

**Issue by AmitMY** [fletcher/MultiMarkdown-6#191]
For continuous integration platforms, it is wasteful to always recompile this package (both in terms of time, and electricity).

Could you add a release for ubuntu?

Right now I use github actions to do:
```sh
git clone -b 6.5.2 https://github.com/fletcher/MultiMarkdown-6 multimarkdown
cd multimarkdown
make
cd build
make
mv multimarkdown /usr/local/bin/multimarkdown
```

Where if there was a release of it, I could just do:
```sh
wget -O /usr/local/bin/multimarkdown https://some-path/multimarkdown
```

(building on github actions takes 2 minutes and 10 seconds)

**Comment by fletcher** [comment]
Or you could compile and do:

`wget -O /usr/local/bin/multimarkdown https://your-server.net/multimarkdown`

You don't need me for this.  ;)

There are too many architecture/OS variants when it gets into *nix, and I have no desire to maintain that (outside of the core source.) So I will not be doing this at this time.
