### ISSUE TITLE
Rowspan in tables or multiline cells

### ISSUE THREAD

**Issue by noursbleu** [fletcher/MultiMarkdown-6#192]
Hi !
I'm writing science with MMD since a week now and it's great. Just 2 points :
* Is there a way to do rowspan like in this example below? I can't find anything in help guide. 
```
|:--:|:--:|:--:|
|Cell 1| Cell 2 |Cell 3|
| ^^    | Cell 4 | Cell 5|
```

![table](https://user-images.githubusercontent.com/46239621/94937680-31ca9200-04d0-11eb-8653-9996946826c9.png)

* How can one make multiline cells ? `<br>` doesn't seem to work in a cell.

```
|:--:|:--:|:--:|
|Measures| Measure 1<br>(unit1) |Measure 2<br>(unit2)|
| Results    | 12,56 | 23,56|
```
![table2](https://user-images.githubusercontent.com/46239621/94939537-9686ec00-04d2-11eb-98a7-f43c76f35c22.png)

Thank you very much for your hard work and sorry for my pretty bad english writing...
Best regards.
NC

**Comment by fletcher** [comment]
Your English was fine!

There is no way to specify rowspan in MultiMarkdown -- you would have to use HTML to do this.

As for multiline cells -- `<br>` works just fine (as you can see from your example above).

**Comment by noursbleu** [comment]
Thank you.
You're right, <br> works just fine. I did a mistake somewhere...
Bad news for rowspan... This tables can be used in Joplin or Markdown-it, so I thought it was possible
to implement this feature in a future multimarkdown version.
Anyway, thank you for your answer !
Nicolas
