### ISSUE TITLE
LICENSE.txt and README.txt are installed in /usr/local

### ISSUE THREAD

**Issue by yasuhirokimura** [fletcher/MultiMarkdown-6#193]
I tried install of 6.6.0 on Debian 10 with following steps.

1. Download MultiMarkdown-6-6.6.0.tar.gz
2. `tar xfpvz MultiMarkdown-6-6.6.0.tar.gz`
3. `cd MultiMarkdown-6-6.6.0`
4. `make release`
5. `cd build`
6. `make`
7. `make install`

Then I found `LICENSE.txt` and `README.txt` are installed in `/usr/local`. But they should be installed somwhere else (`/usr/local/share/doc/MultMarkdown`, for example).

**Comment by fletcher** [comment]
Fixed (I think) in `develop` branch.  Will be pulled to `master` with the next version.

Thanks!  And let me know if this commit does not fix it correctly.

**Comment by yasuhirokimura** [comment]
I checked out `develop` branch and confirmed this problem is fixed.
Thank you for quick response.

**Comment by fletcher** [comment]
Thank you for suggesting an improvement!
