### ISSUE TITLE
Conversion latex - pdf: LaTeX Error: Missing \begin{document}

### ISSUE THREAD

**Issue by arteteco** [fletcher/MultiMarkdown-6#196]
Hello everyone,
I'm trying to create a pdf from a mmd file. 
When I do the conversion to pdf, I get this error: `! LaTeX Error: Missing \begin{document}.`.

This is the content of my md file

```
Title: Sample  
Author: arteteco  
Date: 2020-12-27
Language: English  

This is some random test just to reproduce the conversion. **Love to all**!
```
I then run

```
multimarkdown sample.md -t latex > sample.tex
```

and get the following `sample.tex`

```
\def\mytitle{Sample}
\def\myauthor{arteteco}
\def\mydate{2020-12-27}
\def\language{English}

This is some random test just to reproduce the conversion. \textbf{Love to all}!
\end{document}
```

Now with `pdflatex` I try the conversion and this is the output

```
$ pdflatex sample.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./sample.tex
LaTeX2e <2020-10-01> patch level 2
L3 programming layer <2020-12-07> xparse <2020-03-03>

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 T
     his is some random test just to reproduce the conversion. \textbf{Love ...

? 
```

* **OS:** Debian 10
* **MMD version**: MultiMarkdown 6 v6.6.0
* **pdflatex version**: pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)

I guess multimarkdown should add the `\begin{document}` automatically?

Thanks everyone!

**Comment by arteteco** [comment]
My bad, I didn't read the docs properly.
For newcomers: you have to create a document for preamble and one for footer, and link them in the markdown with something like this. This is metadata so has to go at the beginning at the document.

```
latex begin: latBegin.txt
latex footer: latEnd.txt
```

**Comment by fletcher** [comment]
I've been busy and have not had a chance to respond.

Yes -- you need additional information to form a complete LaTeX document.  You can create your own (as you did), or use the default types by specifying one of them in the metadata (e.g. `latex config: article`)

<https://fletcher.github.io/MultiMarkdown-6/syntax/metadata.html#latexconfig>
