### ISSUE TITLE
Glossaries not implemented

### ISSUE THREAD

**Issue by fletcher** [fletcher/MultiMarkdown-6#2]
Need to implement glossary support.

**Comment by fletcher** [comment]
I'm considering changing the way that glossaries work.  When first implemented, I basically coopted the footnote syntax to take on an extra feature.

MMD-6 represents a good stopping point to consider re-thinking this (along with other things.)  I think that coming up with a more cohesive strategy for abbreviations and acronyms makes sense, but I'm not sure yet what that will look like.

I welcome thoughts and input!

**Comment by sgbotsford** [comment]
A use for acronyms that I have frequently seen is TANSTAAFL (There ain't No Such Thing as a Free Lunch) on the first use of a term.  Another common practice I've seen is to put the first occurrence of a new word in *italics* with the definition following in parentheses if short, or as a footnote if long.

I think html5 allows the creation of new tags that can be styled with CSS.  Is HTML 5 well enough supported that you can drop support for the earlier ones?  This would require some form of  user based mapping between MD constructs and tags.  If done right, then the HTML5 mapping would be a superset  of the html<5 mappings.

**Comment by fletcher** [comment]
I added support for glossary terms to the `develop` branch.  The syntax is different than previous versions of MMD.

Previously, glossary entries hijacked the footnote syntax.  This was an artifact of the fact that HTML doesn't support glossaries, and that the original LaTeX output was created by transforming HTML into LaTeX.

In MMD-6, footnotes, citations, and glossary terms are all converging on the same parsing structure.  They rely on different leading characters inside the brackets (e.g. `[^foo]`, `[#foo]`, and now `[?foo]`).  All three allow inline variants as well as definition by reference. In the case of glossary terms, the inline variant requires that the term itself immediately follow the `?` and be wrapped in parentheses.

	Let's talk about [?MultiMarkdown], as well as [?(Markdown) Markdown is a lightweight...].

	[?MultiMarkdown]: MultiMarkdown is a "descendant" of Markdown.


I'm still tinkering with this, but let me know what you think!

**Comment by fletcher** [comment]
I think the new glossary syntax is better than the old one.  There may still be room for some improvement.

See <https://github.com/fletcher/MultiMarkdown-6/wiki/Changes-from-MMD-5> for more information.
