### ISSUE TITLE
escape characters are not correctly unescaped in URLs

### ISSUE THREAD

**Issue by af4jm** [fletcher/MultiMarkdown-6#207]
If I have the following Markdown link...

`[YouTube vid](https://www\.youtube\.com/watch?v=2SJ977\-CMPg&amp;t=360)`

it should generate the following HTML

`<a href="https://www.youtube.com/watch?v=2SJ977-CMPg&amp;t=360">YouTube vid</a>`

but instead it leaves the escaping backslashes in, and changes the `&` to `&amp;` resulting in a malformed URL

I see the issue in Textastic for iOS, but after filing a bug [over there](https://feedback.textasticapp.com/en/communities/1/topics/3583-opening-a-markdown-link-in-safari-mishandles-escapes), they tell me they're also able to reproduce in Marked 2 (if MultiMarkdown is used but not if Discount is used)

**Comment by af4jm** [comment]
here's some Markdown to check if escapes are handled correctly (if the 2 lines render the same strings of characters, it passes, if the first line has extra backslashes, it fails)

``` Markdown
\!\#\(\)\*\+\-\.\[\\\]\^\_\`\{\|\}\~\
``!#()*+-.[\]^_`{|}~``
```

**Comment by fletcher** [comment]
See if the latests commits in `develop` fix your results.

Thanks!
