### ISSUE TITLE
Suggestion: add token type TEXT_REPLACEMENT_CHARACTER to ease skipping NSTextAttachments

### ISSUE THREAD

**Issue by DivineDominion** [fletcher/MultiMarkdown-6#216]
Text Kit on iOS and macOS uses the ["Object Replacement Character" (U+FFFC, "\u{0000fffc}")](https://unicode-table.com/en/FFFC/) to denote rich text contents or decorations inside text.

The way this works is basically that this is a zero-length character in the string, and there's a text attribute (the key is [`NSAttachmentAttributeName`](https://developer.apple.com/documentation/uikit/nsattachmentattributename?language=objc)) that is e.g. of the type `NSTextAttachment`.

Setting this is useful to show inline views in editors -- like images, buttons, "pills" (i.e. the tokens of token fields).

If MMD6 recognizes this character as a special case, it'd be easier to keep the attribute around. Could be a sibling to the `TEXT_PLAIN` token type, or maybe even a child, because it's _both_ plain text _and_ a replacement character, like `TEXT_REPLACEMENT_CHARACTER`.

The character is irrelevant when converting to e.g. HTML and should be skipped; for syntax highlighting, it's quite useful though.

**Comment by fletcher** [comment]
I'll look into this.  Thanks.
