### ISSUE TITLE
GLib / GLibFacade mentioned in frontmatter of source files but not used

### ISSUE THREAD

**Issue by DivineDominion** [fletcher/MultiMarkdown-6#226]
I believe the passing reference to GLib is outdated in source files:

	GLibFacade.c and GLibFacade.h are from the MultiMarkdown v4 project:

		https://github.com/fletcher/MultiMarkdown-4/

Also in d_string.h:

     /* WE implement minimal mirror implementations of GLib's GString
     * sufficient to cover the functionality required by MultiMarkdown.
     *
     * NOTE: THese are 100% clean, from-scratch implementations using only the
     * GLib function prototype as guide for behavior.
     */

Does removing this sound about right? @fletcher

**Comment by fletcher** [comment]
No. This should stay. 

Originally, the first C version of MultiMarkdown was a fork of peg-markdown, which required the entire glib library simply to add dynamic string support. 

Daniel Jalkut helped by starting a new single file replacement GString implementation, which was subsequently renamed d_string. I have made some tweaks and additions over the years, but that is the origin of that particular file.
