### ISSUE TITLE
Interoperable YAML Schema?

### ISSUE THREAD

**Issue by elsiehupp** [fletcher/MultiMarkdown-6#227]
As best I can tell, MultiMarkdown uses a subset of YAML for metadata headers. There's [this guide section](https://fletcher.github.io/MultiMarkdown-4/metadata.html) on the topic, but it's from MultiMarkdown 4, not MultiMarkdown 6.

The Markdown-based notes editor Joplin is [currently in the process of working on YAML compatibility](https://github.com/laurent22/joplin/issues/5224). Could you perhaps pop in and give your thoughts on interoperability with MultiMardown? (YAML aside, it would be nice to have some guidance on packaging multiple markdown files with attachments.)

Something I mentioned in the Joplin issue comment thread is the possibility of using [Schema.org](https://schema.org/) for metadata formatting. In the case of Joplin, this would most likely default to [`NoteDigitalDocument`](https://schema.org/NoteDigitalDocument), but MultiMarkdown presumably supports a wider range of use cases. While the metadata fields supported by Schema.org are... quite numerous, MultiMarkdown and/or Joplin could choose their supported fields from the Schema.org list and define behavior for losslessly handling valid metadata fields that aren't supported by a particular client.

I guess, in summary:

1. Can you coordinate with Joplin to some extent so that Joplin's exports can be agreeable with MultiMarkdown and vice versa?
2. Can you provide perspective and guidance on packaging?
3. Can you consider using Schema.org for defining standardized metadata fields? And,
4. Can you update the MultiMarkdown guide for version 6 to define the current practices with regard to metadata headers?

Thanks!

**Comment by fletcher** [comment]
At this time I am not interested in modifying MultiMarkdown's metadata approach, nor does it require any sort of standardization.  MultiMarkdown's metadata is designed to be flexible and support many different use cases.  It's up to the user to decide whether to standardize on certain metadata keys.

As for interoperability, I *believe* the MultiMarkdown metadata syntax is fairly well documented, and there are a few test cases in the test suite.

I am happy to answer any specific questions that are sent my way.

**Comment by elsiehupp** [comment]
No worries! Regardless, if you’d like you could stop by and say hi at [the ongoing Joplin YAML initiative](https://github.com/laurent22/joplin/issues/5224).
