### ISSUE TITLE
Tokenization:  GitHub-style checkbox list's token before the brackets is wrong

### ISSUE THREAD

**Issue by DivineDominion** [fletcher/MultiMarkdown-6#228]
This input:

```
- [ ] Test
```

produces this token tree (simplified print-out of location + length pairs):

```
{0,10}TokenType.blockListBulleted
{0,10}TokenType.blockListItemTight
{0,10}TokenType.lineListBulleted
{0,1}TokenType.markerListBullet
{2,0}TokenType.textPlain            <---- should be {1,1}
{2,3}TokenType.pairBracket
{2,1}TokenType.bracketLeft
{3,1}TokenType.textPlain
{4,1}TokenType.bracketRight
{5,5}TokenType.textPlain
```

In MMD6's own output (with enum ints):

```
* (0) 0:10	'- [ ] Test'
	* (70) 0:10	'- [ ] Test'
		* (75) 0:10	'- [ ] Test'
			* (20) 0:10	'- [ ] Test'
				* (198) 0:1	'-'
				* (220) 2:0	''               <---- should be {1:1} and not an empty string
				* (107) 2:3	'[ ]'
					* (135) 2:1	'['
					* (220) 3:1	' '
					* (136) 4:1	']'
				* (220) 5:5	' Test'
```

**Comment by fletcher** [comment]
No...  The 2:0 token is the beginning of the text content after the hyphen/dash, but leading whitespace is stripped out since it is longer needed once the line has been determined to be a bulleted list item.  So this token should be an empty string.

**Comment by DivineDominion** [comment]
I see. That's a peculiar/odd detail, but thanks for the explanation!

**Comment by fletcher** [comment]
The thing to remember is that by the time you interact with the token tree like this, it represents a semantic understanding of the document, not just a tokenization of the text.  This includes stripping out whitespace that should not appear in the final output, among other things.  It also has to balance this with maintaining enough information for syntax highlighting purposes (if desired).
