### ISSUE TITLE
Empty line after indented code block not recognized as BLOCK_EMPTY, not its newline as TEXT_NL

### ISSUE THREAD

**Issue by DivineDominion** [fletcher/MultiMarkdown-6#232]
Given this MMD:

```mmd
text

    code1
    code2

more
```

The token tree description (with literal newlines replaced with `\n` to help readability) is:

```
=====>
* (0) 0:31	'text\n\n    code1\n    code1\n\nmore'
	* (77) 0:5	'text\n'
		* (223) 0:4	'text'
		* (218) 4:1	'\n'
	* (60) 5:1	'\n'
		* (218) 5:1	'\n'
	* (52) 6:20	'    code1\n    code1\n'
		* (223) 10:5	'code1'
		* (218) 15:1	'\n'
		* (223) 20:5	'code2'
		* (218) 25:1	'\n'
	* (77) 27:4	'more'
		* (223) 27:4	'more'
<=====
```

Note the bottom-most 3 lines:

```
		* (218) 25:1	'\n'
	* (77) 27:4	'more'
		* (223) 27:4	'more'
```

The range `26:1` is essentially missing.

The expected output for a token tree that describes the document correctly at character position `26`, I'd expect a BLOCK_EMPTY + TEXT_NL:

```
=====>
* (0) 0:31	'text\n\n    code1\n    code1\n\nmore'
	* (77) 0:5	'text\n'
		* (223) 0:4	'text'
		* (218) 4:1	'\n'
	* (60) 5:1	'\n'
		* (218) 5:1	'\n'
	* (52) 6:20	'    code1\n    code1\n'
		* (223) 10:5	'code1'
		* (218) 15:1	'\n'
		* (223) 20:5	'code2'
		* (218) 25:1	'\n'
	* (60) 26:1	'\n'                                     <----------
		* (218) 26:1	'\n'                             <----------
	* (77) 27:4	'more'
		* (223) 27:4	'more'
<=====
```

@fletcher Would you agree that this is an issue worth tracking for the future?

**Comment by DivineDominion** [comment]
Thanks for the explanation! I wanted to report this because it looked odd that the token tree's description had gaps: If the code block continued one line further down, I would have just thought that this is MMD6's way to interpret the situation. The gap looked suspicious and I didn't notice any mentioning of intentional gaps in the headers or source files, so I figured you might not be aware of this as well.

So this is a "wontfix because intentional" situation :)

**Comment by fletcher** [comment]
Or maybe a "quasi-intentional" situation and will consider fixing if there is a situation where it actually matters.

:)

**Comment by fletcher** [comment]
(But thank you for noticing!!)
