### ISSUE TITLE
The first line containing a : (colon) is always treated as metadata

### ISSUE THREAD

**Issue by nickasd** [fletcher/MultiMarkdown-6#235]
I was just trying to convert a Markdown document to HTML but it always turned out to be empty. After some time I figured out that this is due to the first phrase in the first line containing a colon. Unless the text before the colon contains a special character like `ä` or a Markdown sequence like `> ` or `#`, it is treated as metadata and hence the rest of the document until the first empty line doesn't appear in the HTML file. Is it supposed to work like this, i.e. even if the text before the colon is a sequence of words separated by whitespaces, or just some bogus text (like "asdfasdf")? How can I begin a text with a line containing a colon and treat it as normal text?

**Comment by fletcher** [comment]
You can either disable MultiMarkdown's advanced features (compatibility mode) and stick to strict Markdown (which doesn't support metadata), or you can put a leading blank line, or escape the colon (`foo\: bar`).

**Comment by nickasd** [comment]
Thank you. I just think it's confusing that a sentence like "Alice said: Here I am." is treated like metadata and the similar sentence "Zöe said: Here I am." is not. Wouldn't it be better if only recognised keywords were treated as metadata?

**Comment by fletcher** [comment]
No, because there is an infinite possible number of keywords, and I can't begin to predict what any given user would want to use.

**Comment by nickasd** [comment]
I see. I thought that they were Multimarkdown directives, but apparently they can be used for the output format, too. Well, at this point I would just like to say that as useful as metadata may be, it‘s the only thing until now that has given me some trouble when converting to HTML: it can look like regular text and, more importantly, regular text can be mistaken for metadata by the parser (whereas a human could probably tell what it is). Otherwise Multimarkdown directives are always characterised by some rarely used character.

**Comment by fletcher** [comment]
Colons are not normally used that way in English, which may explain why it hasn't been an issue.

MultiMarkdown ignores colons in URLs (since those are common), and colons on the end of the first line.  Otherwise, I don't think I've had more than one or two issues over the years.  And a leading blank line takes care of it for me.
