### ISSUE TITLE
[Feature request] File transclusion on remote raw sources

### ISSUE THREAD

**Issue by vinibali** [fletcher/MultiMarkdown-6#237]
hello there!

is there a way to use file transclusion on remote raw sources?
in my case I'm storing all the md and source files for my WP blog at GitLab.
it's possible, that is this feature already works and I just messed up the path at wp-config.php

[reason to open](https://github.com/mytory/mytory-markdown/issues/11)

**Comment by fletcher** [comment]
I'm not sure I follow you -- MultiMarkdown can transclude any local file for which it has read permission.  If MultiMarkdown is running on the server, then it can access any accessible files on the server.  Permissions and file paths would be determined by the server configuration of course.

**Comment by vinibali** [comment]
Yes, that's pretty clean, thank you for the explanation.
However I'm using a markdown plugin for Wordpress. This plugin can create the content from a URL, like one which points to my GitLab repo's raw source.
In order to use file transclusion with that plugin, MMD would be the tool.
However I'm storing all my files in a remote GitLab server, that's not working at the moment.
I was just wondering if I could tell MMD, to use a remote file to process.

The first post was not well defined, sorry for that.

**Comment by fletcher** [comment]
Then, no -- MultiMarkdown does not support transclusion of remote content.  You could modify it to to do so, of course, but not something I am looking at doing right now.

**Comment by vinibali** [comment]
Thanks
