### ISSUE TITLE
Automatic abbreviation processing is not reliable

### ISSUE THREAD

**Issue by vatonbero** [fletcher/MultiMarkdown-6#239]
Hi there,

I have [discovered](https://fletcher.github.io/MultiMarkdown-6/syntax/abbreviations.html) abbreviation processing in MultiMarkdown 6 and I have started using it. 

I have noticed unusual processing: if you have several abbreviated words in the document, only the last one will be processed with correct html tag and every one before it will have abbreviated title inline. Here is an example:

```source code
Something something HTML

Lorem HTML something ipsum something

[>HTML]: Hyper Text Markup Language
```

This will translate to:

```
Something something Hyper Text Markup Language (<abbr title="Hyper Text Markup Language">HTML</abbr>)

Lorem <abbr title="Hyper Text Markup Language">HTML</abbr> something ipsum something
```

Program acts even weirder if you try to use 10 occurrences in the file: it might not process some strings and it will just leave them without html tags of any sort. My expectation was to process each found string and replace it with appropriate abbreviation html code.

**Comment by fletcher** [comment]
The behavior you included is correct.  The first usage includes the full term, and presents the abbreviation.  Only the abbreviation is included in subsequent uses.

As for the "10 occurrences" -- if you envision a MultiMarkdown document as a parse tree, some of the branches do not make sense for applying abbreviation syntax (e.g. code blocks and code spans...)

If you provide an example, I can look to see if the behavior needs to be modified to fix excluded branches.

Thanks!

**Comment by vatonbero** [comment]
> The behavior you included is correct. The first usage includes the full term, and presents the abbreviation. Only the abbreviation is included in subsequent uses.
> 
This makes sense, yes! It would be okay to have a trigger to change this behaviour simply because we might not want to include full term at all on page and just have abbr tag


> If you provide an example, I can look to see if the behavior needs to be modified to fix excluded branches.
> 
> Thanks!

Right now I cannot reproduce this anymore because Mardkown files have been restructured in the meantime however I think I have spotted another something.

Thanks!
