### ISSUE TITLE
Build warning and question on directory for option

### ISSUE THREAD

**Issue by wnm3** [fletcher/MultiMarkdown-6#247]
I am building on a newer MacBook Pro with the M1 CPU. When running make in the build directory, I got a warning and a comment about a lib directory:

```
/Users/wnm3/csnext/MultiMarkdown-6/src/argtable3.c:3853:107: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
TREX_API TRex * trex_compile(const TRexChar * pattern, const TRexChar ** error, int flags) __attribute__((optimize(0)));
                                                                                                          ^~~~~~~~~~~
1 warning generated.
[ 97%] Building C object CMakeFiles/multimarkdown.dir/src/textbundle.c.o
[100%] Linking C executable multimarkdown
ld: warning: directory not found for option '-L/usr/local/opt/qt/lib'
[100%] Built target multimarkdown
```
It appears to have built correctly but I'm concerned if I need to install something as there is no /usr/local/opt/qt directory on my system.

Thanks for fixing the table issue.

**Comment by wnm3** [comment]
Also, how to build a new MMDComposer5.app (or 6...)?

**Comment by fletcher** [comment]
I'm not sure why you're seeing a reference to `qt` (I assume this is a reference to the Qt UI software???)  I don't use it or link to it for anything related to the MultiMarkdown project.

If you're concerned about whether MultiMarkdown compiled correctly, you can run `ctest` from the build directory and ensure that it passes all tests.

As per other thread, Composer is a commercial app.  So you can't build it.  ;)

**Comment by wnm3** [comment]
It must not have built as there is no ctest nor CTest nor Ctest anywhere in the repo (including build). There is an executable multimarkdown though. There is no make debug but make release worked.

The original error was my fault. It was a leftover LDFLAGS entry in the .zshrc from a brew install qt on an older MacBook.
