### ISSUE TITLE
Please consider adding option to hide Markdown source and search windows in MMDComposer

### ISSUE THREAD

**Issue by wnm3** [fletcher/MultiMarkdown-6#248]
Often I want to compare the Markdown I've produced with a web page. It would be nice to just see the rendered markdown in a window by itself without having to hide the other parts of the display.

**Comment by fletcher** [comment]
MultiMarkdown Composer is a separate (commercial) application.  Support is [here](https://multimarkdown.zendesk.com/hc/en-us/community/topics/4606065324051-MultiMarkdown-Composer-Beta) (migrating here) or [here](http://support.multimarkdown.com) (older support site, but still in use).

This github project is the open-source MultiMarkdown command-line utility.

**Comment by wnm3** [comment]
Thank you for publishing fixes in a refresh of the MultiMarkdown Composer. This allows me to show off improved table processing from my OSS site [MDfromHTML](https://github.com/IBM/MDfromHTML)

**Comment by fletcher** [comment]
No worries!
