### ISSUE TITLE
File transclusion happens even when inside a html comment.

### ISSUE THREAD

**Issue by RedBed24** [fletcher/MultiMarkdown-6#253]
As of Multimarkdown v6.7.0, when using transclusion inside a comment: `<--{{other_file}}-->`, the transclusion is processed and the contents of other_file are put.
And behaviour changes depending in the contents of other_file:

# Case 1: other_file gets processed but it doesn't matter

1. Create other_file.md with contents:
```
This shouldn't be visible
```
2. Create file.mmd with contents:
```
Hi
<!--{{other_file.md}}-->
```
3. Parse file.mmd
```
multimarkdown file.mmd
```

Output:
``` HTML
<p>Hi
<!--This shouldn't be visible
--></p>
```

Expected output:
``` HTML
<p>Hi</p>
<!--{{other_file.md}}-->
```

# Case 2: other_file is processed and has comments

1. Create other_file.md with contents:
```
<!--comment-->
This shouldn't be visible
```
2. Create file.mmd with contents:
```
Hi
<!--{{other_file.md}}-->
```
3. Parse file.mmd
```
multimarkdown file.mmd
```

Output:
``` HTML
<p>Hi
<!--<!--comment-->
This shouldn't be visible
--></p>
```

Expected output:
``` HTML
<p>Hi</p>
<!--{{other_file.md}}-->
```

# Case 3: other_file is processed and final content changes unexpectedly

1. Create other_file.md with contents:
```
# Title

This shouldn't be visible
```
2. Create file.mmd with contents:
```
Hi
<!--{{other_file.md}}-->
```
3. Parse file.mmd
```
multimarkdown file.mmd
```

Output:
``` HTML
<p>Hi
&lt;!&#8211;# Title</p>

<p>This shouldn&#8217;t be visible
&#8211;&gt;</p>
```

Expected output:
``` HTML
<p>Hi</p>
<!--{{other_file.md}}-->
```

**Comment by fletcher** [comment]
Transclusion is handled before any MultiMarkdown processing.  This is the proper behavior.
