### ISSUE TITLE
Install failed on macOS Sonoma - How to uninstall completely

### ISSUE THREAD

**Issue by bluelephant825** [fletcher/MultiMarkdown-6#254]
I ran the .pkg, but no app was installed in my Applications folder.

How do I perform a complete uninstall?

UPDATE: Looks like it didn't fail after all! I understand that the pkg doesn't install anything in the Applications folder, but installs a series of mmd files in /usr/local/bin.

**Comment by fletcher** [comment]
Correct -- this is a command-line utility, not an application.
