### ISSUE TITLE
Nested unordered lists are flattened

### ISSUE THREAD

**Issue by martinwguy** [fletcher/MultiMarkdown-6#257]
Fab tool! Exactly what I needed. Many thanks.

Only one discrepancy between multimarkdown's HTML output and codeberg/github's:

My markdown (edited for brevity) is:
```
* mansr's 2015 post says
  When I recently decided to take a closer look at the DSD phenomenon
  - DSF read/write
  - DFF read-only
  - DSD to PCM conversion using the existing resampler
  - PCM to DSD conversion

  The DSD encoding supports four settings
* [Redhat issue 1931407](https://bugzilla.redhat.com/show_bug.cgi?id=1931407)
Add DSD processing of .dsf files to sox
```
and codeberg and github render this as
```
* mansr's 2015 post says
  When I recently decided to take a closer look at the DSD phenomenon
  * DSF read/write
  * DFF read-only
  * DSD to PCM conversion using the existing resampler
  * PCM to DSD conversion
  The DSD encoding supports four settings
* Redhat issue 1931407
  Add DSD processing of .dsf files to sox
```
but multimarkdown renders it as
```
 * mansr’s 2015 post says When I recently decided to take a closer look at the DSD phenomenon
 * DSF read/write
 * DFF read-only
 * DSD to PCM conversion using the existing resampler
 * PCM to DSD conversion

The DSD encoding supports four settings

 * Redhat issue 1931407 Add DSD processing of .dsf files to sox
```

So there are several issues here:
* nested lists not being nested
* text after a list element, indented to the same depth after a newline, being rendered immediately after the list element instead of on a new line at the same indent level
* text indented to a nesting level after a blank line being detached from the previous item and unindented (it ends the unordered list and a new one is started afterwards)

It's arguable that my "Add DSD processing of .dsf files" line should be indented by two spaces, but that's what they got as input and that's how they rendered it (which is what I wanted, if maybe incorrect) so I've left it for completeness.

I've also tried this with git head of MultiMarkdown-6 and get the same result as the Fedora package.

**Comment by fletcher** [comment]
Markdown indents (for code blocks or nested lists) are 1 tab or 4 spaces. 

You seem to be using 2 spaces, which is not enough to trigger an indent in Markdown. (If I misinterpreted your example, let me know - I am on a phone and may have made a mistake.)

Some other markup languages, which are not Markdown but might be based on it, use 2 spaces instead of 4, but that is not the Markdown standard and is therefore not what MultiMarkdown uses.

**Comment by martinwguy** [comment]
I didn't realise that forgejo, github (and gitlab, just tested) used such a maverick version of Markdown and am now better informed, but I don't feel like editing 150 issues and a few dozen wiki pages to make them conform so I'll see about writing a script to convert their formats to kosher Markdown.

Thanks for the fast response and keep up the good work

    M

**Comment by fletcher** [comment]
There is definitely a wide range of divergence from the original Markdown from the various “spin-offs”.  

The most important thing is picking  the tools that work best for you. 

There are, however, some stylistic things you can do that improve the compatibility of your documents across various tools. 

for example, 4 spaces for an indent is more “proper”, and I believe more compatible across tools.  Leaving a blank line after ATX headings is more likely to be compatible. 

That can make it easier when you find for some reason that you are forced to switch tools.
