### ISSUE TITLE
Proposal for quotation marks

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-6#39]
Assuming that `quotes language` will also be implemented in MMD a similar problem with [translations](https://github.com/fletcher/MultiMarkdown-6/issues/37#issuecomment-285500942) exists. Correct quotation marks seem to be quite diverse, as can be found [here](https://en.wikipedia.org/wiki/Quotation_mark). Implementing all the different styles is maybe a bit too much for MMD so I propose a similar approach like in #37 :

```
mmd-lq-primary:        „
mmd-rq-primary:        “
mmd-lq-secondary:      ‚
mmd-rq-secondary:      ‘
```

Respectively:

```
lang:                     fr
mmd-lq-fr-primary:        « 
mmd-rq-fr-primary:         »
mmd-lq-fr-secondary:      “
mmd-rq-fr-secondary:      ”
mmd-lq-de-primary:        „
mmd-rq-de-primary:        “
mmd-lq-de-secondary:      ‚
mmd-rq-de-secondary:      ‘
```

In the example above MMD would use the `mmd-lq-fr-*`and `mmd-rq-fr-*` metadata entries to generate the quotation marks. But maybe like in #37 it's a bit out of scope since it could also be achieved with transclusion.

What isn't clearly visible in the example above (but it is really in the code) is that the value of `mmd-lq-fr-primary` is followed by a half-em non-breaking space (`U+202F, &#8239;`) and the value of `mmd-lq-fr-primary` starts with the same space as suggested [here](https://en.wikipedia.org/wiki/Quotation_mark#French). So MMD should not treat these spaces as ordinary whitespace.

**Comment by fletcher** [comment]
I think this is headed down the wrong path.  I want to streamline metadata, not complicated it.

If there is a system of quotes that should be added to the core source, I'm happy to do add it (or accept pull requests).  If someone wants to customize the behavior for their own needs -- it's easy enough to do that even if you're not a coder.  But adding a complicated metadata scheme doesn't seem like the right path.

As a note, in the 13+ years or so that MMD has been around no one has asked for any more quote characters to be supported.

**Comment by mn4367** [comment]
> If someone wants to customize the behavior for their own needs -- it's easy enough to do that even if you're not a coder.

By regex or search/replace in the editor? A good editor may be able to insert proper quotation marks automatically but everything else is tedious in my opinion or too complex (no offense meant but I think you're over-estimating the knowledge of average users.)

> As a note, in the 13+ years or so that MMD has been around no one has asked for any more quote characters to be supported.

I'd attribute that to a generally declining interest in good typography (in the HTML world).
