### ISSUE TITLE
I am not sure I would call this an issue, but a question about Latex metadata

### ISSUE THREAD

**Issue by tuxtlequino** [fletcher/MultiMarkdown-6#47]
I have been using MMD for several years and I have created a series of templates for LATEX that create reports, letters, books, etc that I use at least once a week. I noticed that now one can select a latex config file by doing the following,

`LaTeX Config:	tufte-handout`

But I cannot find how that is being changed into what I see on the Latex documents created by MMD6. Where is that latex config taking place? I am not sure what I am missing. I am very interested in understanding this process since this is very important for me.

**Comment by fletcher** [comment]
I added some further description of MMD 6 LaTeX support in the QuickStart guide on the develop branch.  It will migrate to master with the next release.

https://github.com/fletcher/MultiMarkdown-6/tree/develop/QuickStart

Basically, if you use a specific naming convention for your latex include files, they will be linked to automatically.
