### ISSUE TITLE
Latex Config file

### ISSUE THREAD

**Issue by tuxtlequino** [fletcher/MultiMarkdown-6#48]
This is a requested enhancement.

I am super excited about the new way MMD6 is dealing with Latex config files. I was accomplishing this in a very convoluted way before this. I am just not sure people understand (I didn't for a while) that one can organize everything inside subdirectories. I was just wondering if whenever you release MMD6, you could include a README.md and organize everything in subfolders to the benefits of those trying to get a hang of MMD2TEX. That way one can see a subdirectory that has "article" "letter" "handout" and keep everything more compartmentalized.

**Comment by fletcher** [comment]
MMD 6 is already released ;)

But, yes I could add subdirectories.

**Comment by fletcher** [comment]
Added to develop branch for inclusion in next release.
