### ISSUE TITLE
Content of code blocks with characters <,>,&,",' is structurally wrong and not escaped

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-6#49]
Before I start to open more issues, is it OK to file bugs at this early stage or should I wait for a stable release?

````
    ````
    <p a="a" b="'" c="&" d="'">lorem</p>
    ````
````

gives

````
<pre><code></code></pre>

<p a="a" b="'" c="&" d="'">lorem</p>

<pre><code>


</code></pre>
````

**Comment by fletcher** [comment]
Actually, if you look closely this was not being recognized as a code black, but rather as raw HTML in between two empty code spans.

The parser was tweaked to improve this in the develop branch for the next release.

It's fine to file bugs -- 6.0.3 has been released already, so not sure what you would be waiting for.  ;)
