### ISSUE TITLE
Are table headers required now?

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-6#50]
Both

````
|------|------|------|
| cell | cell | cell |
| cell | cell | cell |
````

and

````
|      |      |      |
|------|------|------|
| cell | cell | cell |
| cell | cell | cell |
````

no longer produce a table. In MMD 5 they did.

**Comment by fletcher** [comment]
For the moment, at least one header row is required.  I might change that in the future -- will need to test more for adverse effects.

I will track down why an empty header row (your second example) is not working.  That *should* be sufficient, but I can confirm it doesn't work.

**Comment by fletcher** [comment]
Figured out the problem -- the `table_separator` regular expression in `scanners.re` is too lenient, and it allows the first (empty cells) line to count as a table separator line.  I need to rewrite that regular expression, and that should allow the second example to work.

**Comment by mn4367** [comment]
>I might change that in the future

Oh yes please 😄
