### ISSUE TITLE
Proposal: default value for <title> if title: is missing

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-6#52]
An HTML document without  `<title>` (or with an empty one; most whitespace characters are also considered to be empty) doesn't pass the W3C validator. A solution to this could be using the document filename or `stdin` for the title if no title is given in the document.

**Comment by fletcher** [comment]
If you want a title, use a title.  ;)

**Comment by mn4367** [comment]
W3C wants it, not me. ;-)
