### ISSUE TITLE
Fenced Code Blocks not respecting end delimiter

### ISSUE THREAD

**Issue by krontzo** [fletcher/MultiMarkdown-6#53]
See fragment:

     Usando un script en `bash`

     ```bash
     #!/bin/bash
     
     ###### CONFIG
     ACCEPTED_HOSTS="/root/.hag_accepted.conf"
     BE_VERBOSE=false
     
     if [ "$UID" -ne 0 ]
       then
      echo "Superuser rights required"
      exit 2
     fi
     
     genApacheConf(){
        echo -e "# Host ${HOME_DIR}$1/$2 :"
     } 
     ```

     Fin.

Gives a wrong code block producing an HTML but also producing a PDF/LaTeX document.

HTML Code:

```html
<p>Usando un script en <code>bash</code></p>

<pre><code class="bash">#!/bin/bash

</code></pre>

<h6 id="config">CONFIG</h6>

<p>ACCEPTED_HOSTS=&#8220;/root/.hag_accepted.conf&#8221;
BE_VERBOSE=false</p>

<p>if [ &#8220;$UID&#8221; -ne 0 ]
then
 echo &#8220;Superuser rights required&#8221;
 exit 2
fi</p>

<p>genApacheConf(){
 echo -e &#8220;# Host ${HOME_DIR}$1/$2 :&#8221;
}</p>

<pre><code>
Fin.
</code></pre>
```

It produces two code blocks!! I see that the offender is the line `###### CONFIG`; but I should't happend, right?

I uninstalled homebrew multimardown in order to test MM6 6.0.3 for macOS, so I cannot test it under MMD5.

**Comment by fletcher** [comment]
This has already been fixed in the develop branch, or you can wait for next version release for a binary.

Thanks!
