### ISSUE TITLE
Possible enhancement for Language definition in FCBs with Syntax Highlighting

### ISSUE THREAD

**Issue by krontzo** [fletcher/MultiMarkdown-6#54]
The default package for syntax highlighting in MM6-generated LaTeX is `listings`.

For using C++ code and Lua code, this package present two issues:

- For C++, it requires the FCBs to be started as:

     ```
     ```C++
     ```

- For Lua, this does not work since there is not default Lua dialect declared in the package:

     ```
     ```Lua
     ```

I use VIM for editing Multimarkdown files. And I normally create HTML files or PDFs from LaTeX.

Therefore, for syntax highlighting I use the LaTeX default by MMD6 (`listings`) and for HTML the `highlight.js` library; 
I like using the VIM functionality for defining the syntax highlighting of Fenced Code Blocks (FCBs) in Markdown documents; but it does not accept `'C++'` as a language definition: it uses `'cpp'` .

So, for VIM and `highlight.js`, `cpp`  and `lua` work well as shown in the following snippet:

     Let's test syntax highlighting for C++:
     
     
     ```cpp
     int main( int argc, char** argv) {
         char str[] = "Cadena";
         return 0;
     }
     ```
     
     An another in Lua:
     
    ```lua
     
     -- hello.lua
     -- the first program in every language
     
     io.write("Hello world, from ",_VERSION,"!\n")
     ```
     
Then, for these language specifiers to work with `listings` in LaTeX, an alias is required for `C++` and a default dialect is required for `Lua`.

Placing the following two lines in the `mmd6-article-begin.tex`, helps:

```latex
\input{mmd6-title}

\lstset{defaultdialect=[5.3]Lua} % using Lua 5.3 as the default dialect
\lstalias{cpp}{C++}                     % `cpp` is now an alias of `C++`

\begin{document}
```

But it has to be included in all the `mmd6-foo-begin.tex` files.

I do not remember if there is a better way to declare those instructions.

**Comment by fletcher** [comment]
You can declare those wherever is most convenient for you.  You can define a central file that you reference from all the other `mmd6-foo-begin.tex` files, so that you consolidate all of your changes in a single file.  Or you can scatter changes throughout multiple files if each "file type" has different settings.

That's the beauty of leaving these files "outside" of MMD itself -- you can customize your LaTeX documents however you like!
