### ISSUE TITLE
Problems with build

### ISSUE THREAD

**Issue by CliffS** [fletcher/MultiMarkdown-6#60]
On Ubuntu 17.04, I'm having problems building this.

I get a stream of output that starts with the following.  Presumably I'm missing a dependency but I've checked `libidn2-0-dev`.  What am I doing wrong?

```
[ 46%] Built target libMultiMarkdown
[ 48%] Linking C executable multimarkdown
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-netrc.o): In function `Curl_parsenetrc':
(.text+0x3a0): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-curl_addrinfo.o): In function `Curl_getaddrinfo_ex':
(.text+0x73): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o): In function `Curl_disconnect':
(.text+0x6b87): undefined reference to `idn2_free'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o): In function `Curl_disconnect':
(.text+0x6ba3): undefined reference to `idn2_free'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o): In function `Curl_disconnect':
(.text+0x6bbf): undefined reference to `idn2_free'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o): In function `Curl_disconnect':
(.text+0x6bdb): undefined reference to `idn2_free'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o): In function `Curl_disconnect':
(.text+0x6bf7): undefined reference to `idn2_free'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o):(.text+0xa5f6): more undefined references to `idn2_free' follow
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o): In function `fix_hostname.isra.8':
(.text.unlikely+0x2d5): undefined reference to `idn2_check_version'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o): In function `fix_hostname.isra.8':
(.text.unlikely+0x2f0): undefined reference to `idn2_lookup_ul'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-url.o): In function `fix_hostname.isra.8':
(.text.unlikely+0x309): undefined reference to `idn2_strerror'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `destroy_thread_sync_data':
(.text+0x12): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `getaddrinfo_thread':
(.text+0xe8): undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `getaddrinfo_thread':
(.text+0xfe): undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `getaddrinfo_thread':
(.text+0x124): undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `destroy_async_data.isra.1':
(.text+0x16d): undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `destroy_async_data.isra.1':
(.text+0x181): undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `Curl_resolver_is_resolved':
(.text+0x39f): undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `Curl_resolver_is_resolved':
(.text+0x3ac): undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-asyn-thread.o): In function `Curl_resolver_getaddrinfo':
(.text+0x715): undefined reference to `pthread_mutex_init'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-cookie.o): In function `Curl_cookie_add':
(.text+0x10cc): undefined reference to `psl_builtin'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-cookie.o): In function `Curl_cookie_add':
(.text+0x10e5): undefined reference to `psl_is_cookie_domain_acceptable'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-version.o): In function `curl_version':
(.text+0x9d): undefined reference to `zlibVersion'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-version.o): In function `curl_version':
(.text+0xc8): undefined reference to `idn2_check_version'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-version.o): In function `curl_version':
(.text+0xd4): undefined reference to `idn2_check_version'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-version.o): In function `curl_version':
(.text+0xf8): undefined reference to `psl_get_version'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.a(libcurl_la-version.o): In function `curl_version_info':
```

**Comment by CliffS** [comment]
Just tried it on a fairly vanilla Ubuntu 16.04.2 LTS and (after installing cmake) it built fine.

**Comment by fletcher** [comment]
There seems to be an issue trying to get libcurl to work properly on Ubuntu (linux?).  It works fine on macOS.

The only thing libcurl is used for is creating EPUBs with remote assets (images, etc.).  IF you don't need that, can disable checking for libcurl by commenting out this line in `CMakeLists.txt`:

	find_package(CURL)

I haven't had time to dig into why cmake/libcurl aren't playing nicely together here (though I believe your errors are different than what I saw).   The issue may have to do with whether a binary library already exists -- it appears your machine is trying to comple libcurl on its own?

Input welcome.

**Comment by CliffS** [comment]
Certainly taking out that line means it builds fine.

Interestingly on the machine where it built out of the box, it states `-- libcurl not found`.  Although
`/usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0` exists, there is no symlink from `/usr/lib/x86_64-linux-gnu/libcurl.so` as there is on the machine on which it does not build.

So it's not a difference between Linux versions, it's simply whether or not CMake finds `libcurl.so`.

Is that any help?

**Comment by fletcher** [comment]
I think it's two sequential things:

1. If libcurl is *not* found, then no problem -- just ignore it.

2. If libcurl is found, *but* for some reason is "incompatible" in some way, then it fails.

I don't have the time to dig into this now, but the problem seems to be to determine why on some machines that libcurl is found but not successfully used.

**Comment by jasedit** [comment]
In Debian based systems, the base `.so` file is contained in the development version of the package - I would guess you need to install the `libcurl4-gnutls-dev` package to get `/usr/lib/x86_64-linux-gnu/libcurl.so` appear on the system. That should at least alleviate the problem of not finding the base shared library.

I'm not certain that will fix the original problem, but it at least will solve the `libcurl not found` error. The original error looks like several symbols can't be found during the linking stage (suggesting `libidn2`, `libpthread`, and `zlib` aren't available for `libcurl`), but that may be due to using the statically linked `libcurl` instead of the dynamically linked one.

**Comment by CliffS** [comment]
@jasedit I think you've missed the point.  When the `libcurl` library is found, `multimarkdown` fails to build.

**Comment by jasedit** [comment]
My apologies for not being more clear. I was initially commenting on the reason why a fresh install would not contain `libcurl.so`, and then meandered to how that doesn't appear to be directly related to the build error initially reported. It may hint towards the underlying issue (cmake may be searching for/finding the shared library when `find_package` is invoked, then building with the statically linked version, which will have to deal with additional challenges related to [difficulties in statically linked binaries using getaddrinfo](http://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo)), which is a more long winded way of saying "I think @fletcher is right, and here's some more information explaining why." Sorry again for not having an explicit diagnosis or being more clear/helpful.

**Comment by CliffS** [comment]
@jasedit I agree.
@fletcher Out of interest, what is the reason for wanting a statically linked binary on Linux?

**Comment by fletcher** [comment]
If you're compiling yourself, I don't honestly care whether you use static binaries or not.

I get the flexibility of using dynamically linked libraries, but as a user it is so frustrating having to deal with multiple dependencies, different versions, etc.  I want to download a single binary that is self contained and works.  If I copy that binary to another (compatible) machine, I expect it to work.

Statically linking libraries allows a single compiled binary application to run on a wider variety of platforms with less difficulty for the user.  I experimented with preparing some precompiled binaries for *nix for MMD and a couple of other projects -- static linking made this much more feasible without a lot of complication. 

But again, for those compiling for themselves, it doesn't make the least bit of difference to me how libcurl is linked.

**Comment by CliffS** [comment]
Makes perfect sense.  Thanks for explaining and especially thanks for producing such a useful utility.

**Comment by fletcher** [comment]
You can change the CMake to not force static libraries -- let me know if that works for you.

@jasedit - Didn't have time to dig too deep into the link you sent, but it seems to support my assertion that self-contained utilities are more easily used.  ;)

**Comment by fletcher** [comment]
I just pushed a commit to `develop`.  It disables a few settings on Linux -- it does not force static building, for example.  On my Ubuntu VM, it builds properly and uses libcurl to download images when creating EPUBs.  Let me know if you have trouble with it.  Should be pulled into `master` later today.

**Comment by CliffS** [comment]
v6.0.7 builds and works wonderfully.

Many thanks.
