### ISSUE TITLE
Call to access metadata keys?

### ISSUE THREAD

**Issue by jasedit** [fletcher/MultiMarkdown-6#62]
In MMD5, there was a call for extracting the list of metadata keys present in a document/text. It looks like this call no longer exists, or has been moved such that I can't easily find it. If it doesn't exist, would it be possible to re-implement? Or is this relegated to writing a regex to extract the keys?

**Comment by fletcher** [comment]
It hasn't been implemented yet.

**Comment by fletcher** [comment]
Implemented now (in `develop`).

Thanks for your suggestions and contributions!!
