### ISSUE TITLE
Multimarkdown 6.07 translates underscores to <em>

### ISSUE THREAD

**Issue by johnblommers** [fletcher/MultiMarkdown-6#69]
Consider `Test.md` containing only three lines:

```
$H_2SO_4$

* $H_2SO_4$
```

Convert it to an html snippet:

```
multimarkdown -b -t html Test.md
```

Examine `Test.html`:

```
<p><span class="math">\(H_2SO_4\)</span></p>

<ul>
<li><span class="math">\(H<em>2SO</em>4\)</span></li>
</ul>
```

When converting a bulleted item containing math, Instead of emitting underscore characters where it finds them, MultiMarkdown 6.07 incorrectly emits `<em>` instead. Take away the bullet as in the first line of the example and all is well.

**Comment by fletcher** [comment]
Interestingly, adding a newline after the list item resolves the problem as well.

**Comment by fletcher** [comment]
To be honest, I'm not exactly sure why the different lines are parsed differently when it comes to this, but I implemented a fix to avoid the problem.  In addition, it fixes similar issues that can arise inside math spans.
