### ISSUE TITLE
HTML characters are not passed directly to the output

### ISSUE THREAD

**Issue by johnblommers** [fletcher/MultiMarkdown-6#71]
Consider this one-line Markdown snippet:

```
Right arrow &rarr;
```

Process it using code from the develop branch of multimarkdown6:

```
multimarkdown -b -s -t html arrow.md
```

The file `arrow.html` contains:

```
<p>Right arrow &amp;rarr;</p>
```

The ampersand has been converted to an HTML sequence so we don't see a right arrow. We believe the correct output should be:

```
<p>Right arrow &rarr;</p>
```

And then the web browser will display Right arrow &rarr;

This is also true for `&pi` (&pi;) and the usual HTML characters.

What do you think?

**Comment by fletcher** [comment]
Fixed in development branch.  Thanks!

F-
