### ISSUE TITLE
Compliling without converting

### ISSUE THREAD

**Issue by johncja** [fletcher/MultiMarkdown-6#73]
It's a bit strange question, but is there an option to compile *with* transclusion, but *without* converting to another format?

**Before compilation:**

- file1.md
- file2.md
- file3.md

**After compilation:**

- large_file.md

**Comment by fletcher** [comment]
The `mmd` output format will do this.

**Comment by johncja** [comment]
Thanks, it works. I tried "md" and "markdown" and it's a bit absurdly that I don't tried "mmd" )

**Comment by fletcher** [comment]
`multimarkdown --help` will show you the various options.
