### ISSUE TITLE
Windows Installer installs Bash Scripts instead of Batch Files

### ISSUE THREAD

**Issue by chiltie** [fletcher/MultiMarkdown-6#74]
With MMD 6, the windows installer installs the bash scripts instead of the windows batch files. This seems to be a mistake.

**Comment by fletcher** [comment]
You'll take the bash scripts, and you'll like them.

;)

Sorry -- yes, this is clearly a mistake.  Looks like I forgot to modify the `scripts` list in the CMake configuration when creating a Windows installer.  I'll fix it soon.

Thanks for pointing this out!
