### ISSUE TITLE
table text wrapping in pdf

### ISSUE THREAD

**Issue by haliaetus13** [fletcher/MultiMarkdown-6#76]
mmd 6.1.0

I cannot get text in a table cell to wrap when exported to LaTeX pdf.  I've tried adding + to the separator line with no change in the output.

Nevermind...restarting my computer seems to have fixed it?

**Comment by fletcher** [comment]
Table wrapping worked with specific alignment (e.g. left, right, center), but not default ('| --- |').

Just pushed a fix to the develop branch that should fix this for next release.

Thanks!!
