### ISSUE TITLE
Compilation for Windows fails

### ISSUE THREAD

**Issue by fletcher** [fletcher/MultiMarkdown-6#80]
There are apparently two issues:

* Microsoft deprecated the old `mkdir()` function.  This tweak, below, allows compilation, but I have not been able to test it.  This is used when extracting from a zip archive -- not needed for most users, but still.  The following lines need to be added to the top of `zip.c`, and this *might* fix it.  If not, might need to redefine as `_mkdir(A)` instead of `mkdir(A)`:

		// Windows deprecated mkdir()
		#if (defined(_WIN32) || defined(__WIN32__))
		#define mkdir(A, B) mkdir(A)
		#endif

* `realpath()` is not supported on Windows.  Apparently `GetFullPathName()` can be used as a replacement, but I haven't had a chance to implement this and try it on Windows.  `realpath()` was added to `main()` in order to get accurate paths for transclusion support.

If someone who uses Windows can implement fixes and verify they work, I'll accept pull requests on this.  Otherwise, I'm not sure when I'll have a chance to dig into it.

**Comment by f8ttyc8t** [comment]
What specific compiler did you try?

**Comment by fletcher** [comment]
CMake on either Ubuntu or Debian.  CMake is configured to use MinGW

**Comment by f8ttyc8t** [comment]
I successfully compiled using both [cygwin](https://www.cygwin.com/) and [msys2](http://www.msys2.org/).
It works like a charm. Only glitch is dependency on cygwin1.dll or msys-2.0.dll. They must reside in path.

Using Cygwin or Msys is because Makefile depends on several Linux related commands.

**Comment by f8ttyc8t** [comment]
You are cross-compiling it, right?

**Comment by fletcher** [comment]
Yes --- I don't have a Windows development machine, and doing that in VirtualBox seems masochistic to me, since I'm not a Windows developer.  :)

Hence the `make windows` configurations in `Makefile` -- they exist for cross-compiling for Windows on a Linux VM.

**Comment by f8ttyc8t** [comment]
I see.
I'm developing using Windows also, so I will probably be the right one to test.

Need to figure out how to compile using Windows-OS. You know, no bash but limited cmd.exe...

**Comment by fletcher** [comment]
I looked for an online service to automatically generate new Windows builds (I started using Travis for CI testing).  I haven't found one, and it's probably more than I can take on at the moment anyway.

But even just getting the above functions replaced in order to cross-compile on Linux would be a big step.

**Comment by f8ttyc8t** [comment]
Already working on it.

**Comment by f8ttyc8t** [comment]
I think I found a fix for mkdir() and realpath().

You've mentioned it's only related to ZIP files. Do you have any testing scenarios I can work with?
(I have no clue how a zip file fits into this tools usage...)

**Comment by f8ttyc8t** [comment]
mkdir() and realpath() are probably fixed (sorry, have no idea how to issue a pull request...).

But creating e.g. odt file generates invalid (zip) file.
Should not be related to mkdir() - I've checked zip.c:unzip_archive_to_path() but I did not find function to be called somewhere.

**Comment by fletcher** [comment]
mkdir is used in `unzip_archive_to_path()` in the event that a subdirectory needs to be made, or the target path doesn't exist yet.

Right now that function is only used when creating a TextBundle document -- we build the zipped version first, and then unzip to create the final document.  This would not normally be used on Windows, but there is no reason it couldn't be.  (It's a Mac file format, and not a commonly used one at that.)

**Comment by fletcher** [comment]
To test, you could use a MMD text file that references a local image.  

`multimarkdown -b -t bundle file.md`

This should create a folder (`file.textbundle`) that should have a subfolder (`assets`) containing the image.

**Comment by f8ttyc8t** [comment]
Gave it a try. 
It seems both mkdir as well as realpath are working as expected. 
Directory structure  `file.textbundle\assets` is being created an contains all file references .

BUT: neither bundle nor odt files are created properly. 
Both having invalid file structure. Also, embedded image-files (located in file.texbundle/assets) are truncated. 
PNG files are 5 bytes of size (containing [PNG file signature](http://www.libpng.org/pub/png/spec/1.2/PNG-Structure.html])), JPG files vary in file size but are far from being complete (probably only containing .

Configurations:
MinGW-w64 crosscompiling on Mac for Windows: FAIL
Windows-build using Cygwin: PASS
Windows-build using msys2: PASS
Mac native build: PASS

I've attached my findings + modified code.
[MultiMarkdown-6.Test.zip](https://github.com/fletcher/MultiMarkdown-6/files/1251062/MultiMarkdown-6.Test.zip)

**Comment by fletcher** [comment]
Strange -- I haven't noticed any problems with images on my machine.

I ran `unzip -t file.zip` to validate, and did get errors related to the directories.  I changed the code to store the directory entries without compression (figuring an empty directory probably can't really be compressed much).  That silenced the warnings.  Pushed build to `develop`.  See if that fixes the problem for you. (Basically just changed `MZ_BEST_COMPRESSION` to `MZ_NO_COMPRESSION` in the 4 or 5 places where a directory is added to a zip file.  (searching for `/", NULL` will find those lines if you want to make the changes manually)

**Comment by f8ttyc8t** [comment]
Sorry - did not change anything.
Results are still the same.
[MultiMarkdown-6.test.zip](https://github.com/fletcher/MultiMarkdown-6/files/1252180/MultiMarkdown-6.test.zip)

**Comment by fletcher** [comment]
Depending on exactly what I do, the images you sent don't seem to work well.  Images from my machine do.

**Comment by f8ttyc8t** [comment]
Would you mind to drop a working image I can test with?
Images I used worked well with my other build. At least I think so...

**Comment by fletcher** [comment]
I use this one:

<https://github.com/fletcher/MultiMarkdown-Gallery/blob/master/Sample-Document/Nautilus_Star.png>

**Comment by f8ttyc8t** [comment]
Nope, same result.
Embedded/included PNG became 5 bytes of size.

So I changed all occurences of `MZ_BEST_COMPRESSION` to `MZ_NO_COMPRESSION`.
bundle version still not works - PNG file (`file.textbundle\assets\Nautilus_Star.png`) gets truncated.

Also, as soon ZIP library gets involved, there are still troubles.
Without compression, file size increased, but archive (odt) still is invalid.

So I did a binary compare. The main differences I found are:
- 0x0D became 0x0D 0x0A (CR/CRLF)
- header is slightly differen
- "Windows"-zip file suddenly ends...

I've attached results - maybe they are of help.
[MultiMarkdown-6.Test.3.zip](https://github.com/fletcher/MultiMarkdown-6/files/1252748/MultiMarkdown-6.Test.3.zip)

Maybe it's somehow related to how source images are read from disk?

**Comment by f8ttyc8t** [comment]
Found first fix. 
Currently fixes "bundle" type only.

Problem is related to transluce.c -> DString * scan_file(const char * fname) and seems to apper in Windows builds only.
Windows requires binary files to be opened in `"rb"` mode.

Fix: replace transluce.c, line 271
`if ((file = _wfopen(wstr, L"r")) == NULL) {`
by
`if ((file = _wfopen(wstr, L"rb")) == NULL) {`

That should do the trick, modified file is [attached ](https://github.com/fletcher/MultiMarkdown-6/files/1262849/transclude.zip).


Anyway, odt files still do not contain images. Probably its a similar problem?
(I did not dig deep enought into that scope of you program)

**Comment by fletcher** [comment]
That same routine (`scan_file()`) from `transclude.h` is used everywhere that a file from disk needs to be read into memory (whether it be a text file for transclusion, or a binary image file).

**Comment by fletcher** [comment]
This is a build with these changes (pushed to `develop` branch)  compiled on Ubuntu.  Can you see whether it works?

Thanks!!

[MultiMarkdown-Windows-6.2.0.exe.zip](https://github.com/fletcher/MultiMarkdown-6/files/1263212/MultiMarkdown-Windows-6.2.0.exe.zip)

**Comment by f8ttyc8t** [comment]
It works except several issue.

Mentioned executable also creates crippled files for e.g. latex or html - but I am not sure yet, whether this is related to development branch changes.
[Results from testing latex generation](https://github.com/fletcher/MultiMarkdown-6/files/1263236/tex-test.zip).

**Comment by f8ttyc8t** [comment]
Works except some issues.

ODT still is invalid, as is latex and html generation.
(But I am not sure whether this is because of using `develop` branch)

See [files](https://github.com/fletcher/MultiMarkdown-6/files/1263290/tex-test.zip)  generated by both msys and your exe.

**Comment by f8ttyc8t** [comment]
Btw. I already tried to replace fopen(...."w") by fopen(..."wb") but this did not solve that.

**Comment by fletcher** [comment]
`develop` branch (aside from ? Windows issues) is fine.

**Comment by f8ttyc8t** [comment]
Well. That's quite strange then.
Think this will require little more time to investigate.

**Comment by fletcher** [comment]
I appreciate your help!

**Comment by f8ttyc8t** [comment]
I think Windows related issues are resolved.
Problem is related to "hand knitted" vasprintf() routine in d_string.c
It seems assumtions taken are not entirely valid in Microsoft/MinGW implementation.

Briefly, I replaced:
```
int vasprintf(char** strp, const char* fmt, va_list ap) {
...
	char tmp[1];
	int size = vsnprintf(tmp, 1, fmt, ap2);
```
by
```
int vasprintf(char** strp, const char* fmt, va_list ap) {
...
#if (defined(_WIN32) || defined(__WIN32__))
	char *tmp = NULL;
	int size = vsnprintf(tmp, 0, fmt, ap2);
#else	
	char tmp[1];
	int size = vsnprintf(tmp, 1, fmt, ap2);
#endif
```

See [fixed d_string.c](https://github.com/fletcher/MultiMarkdown-6/files/1266373/d_string.zip) attached.

**Comment by f8ttyc8t** [comment]
Btw. odt, latex, bundle etc seems now to work in Windows build also.

**Comment by fletcher** [comment]
I compiled on Ubuntu.  Can you verify that I included your fixes properly by checking that this binary passes your tests?

When I compile using MinGW, I get the following warning:

	/home/fletcher/MultiMarkdown-6/Sources/libMultiMarkdown/miniz.c: In function ‘mz_freopen’:
	/home/fletcher/MultiMarkdown-6/Sources/libMultiMarkdown/miniz.c:2948:5: warning: implicit declaration of function ‘freopen_s’ [-Wimplicit-function-declaration]
	     if (freopen_s(&pFile, pPath, pMode, pStream))

I wonder if this is an MinGW error rather than a miniz error?  (I tried updating miniz to the latest version, with no change.)

[MultiMarkdown-Windows-6.2.0.exe.zip](https://github.com/fletcher/MultiMarkdown-6/files/1267616/MultiMarkdown-Windows-6.2.0.exe.zip)

**Comment by f8ttyc8t** [comment]
New version works almost as expected.

1.) `-t odt` file format is not valid for my LibreOffice installation, but fodt is. No clue why.
2.) `-o` (--output) switch seems to be broken. At least it does not work for me. (Using `mulitmarkdown -b -t odt -o hello.odt test.md` still creates `test.odt`). But maybe I'm missing something, because this did not work on previous version(s) either.

**Comment by f8ttyc8t** [comment]
About compiler error: I think it's related to MinGW and installed version only. 
In my MinGW installation, fopen_s is defined in header stdio_s.h when freopen_s is not. 
In contrast, my msys2 version has bot fopen_s and freopen_s defined.

**Comment by fletcher** [comment]
1) What version of LibreOffice are you using?

2) You're using batch mode (`-b`) so `-o` is ignored.

**Comment by fletcher** [comment]
Also -- thanks for testing the build!

**Comment by f8ttyc8t** [comment]
Thanks for `-b` hint! Did not notice that till now...

Using latest version of LibreOffice. As far I've seen, otf (=zip) file is invalid again. But I need to investigate it on my Windows machine later.

**Comment by f8ttyc8t** [comment]
Problem creating invalid odt is related to file open mode ("w" vs "wb") again.

On Linux, and Unix in general, `"r/w"` and "rb/wb" are the same.
Windows behaves (as I learned) slightly different.
I've patched [main.c](https://github.com/fletcher/MultiMarkdown-6/files/1270081/main.zip), lines `480` and `595` to open file in binary (`"wb"`) mode also.
From what I found expecially line 480 is crucial.

See [fopen](https://msdn.microsoft.com/en-us/library/yeby3zcb(VS.71).aspx) 
and [translated mode](https://msdn.microsoft.com/en-us/library/ee2849wt(v=vs.71).aspx).

There are also some other occurrences of `fopen(...,, "w")` which probably also need a fix. But I am not deep enough in entire code to known whether binary mode is crucial for specific scope or not.

**Comment by fletcher** [comment]
An updated build via Ubuntu with the latest changes.  Seems to still work on my Mac.

[MultiMarkdown-Windows-6.2.0.exe.zip](https://github.com/fletcher/MultiMarkdown-6/files/1272983/MultiMarkdown-Windows-6.2.0.exe.zip)

**Comment by f8ttyc8t** [comment]
Looks great now.
(havent' tested beamer and memoir format, because I have no clue what they should look like).

**Comment by fletcher** [comment]
The look largely like regular latex, with a couple of differences.

Thanks for testing it.  I'll go ahead and version bump it!

**Comment by fletcher** [comment]
6.2.1 is now released.

If anyone has trouble with it, please open a new issue.

Thanks @f8ttyc8t for all the help!!!
