### ISSUE TITLE
Support for including latex within markdown via the html comment

### ISSUE THREAD

**Issue by msdailey** [fletcher/MultiMarkdown-6#81]
In mmd-6 is there any chance of continuing to support intermixing latex within markdown input through the html comment (or some other new mechanism).  I found this capability extremely useful: mostly using markdown but extending it where needed with embedded latex.

**Comment by fletcher** [comment]
See <https://github.com/fletcher/MultiMarkdown-6/issues/38>

**Comment by msdailey** [comment]
Thanks for the reference to #38.  I looked for answer in MMD-6 QuickStart guide and did not find it.
Again thanks -- appreciate mmd and mmd composer.
