### ISSUE TITLE
Size of embedded images

### ISSUE THREAD

**Issue by f8ttyc8t** [fletcher/MultiMarkdown-6#83]
Hi,
using latest (6.2.0) MultiMarkdown to convert a file containing images into ODT works pretty well.

I'm curious about why embedded images are reduced to thumbnail size (see attached test file).
Any ideas what I'm doing wrong?

Thanks for great tool!

[minified.zip](https://github.com/fletcher/MultiMarkdown-6/files/1243184/minified.zip)

**Comment by fletcher** [comment]
You didn't specify width or height attributes, so it defaults to whatever OpenOffice prefers (which is apparently very small).

**Comment by f8ttyc8t** [comment]
Ah, thank you!
Didn't think about this reason.
