### ISSUE TITLE
Which is correct syntax?

### ISSUE THREAD

**Issue by lucasimp** [fletcher/MultiMarkdown-6#84]
Hi, I've tried this command:

mmd [myfile] -t html -o newfile.html

but it doesn't work, because the answer is "option -t requires an argument".

Which is correct syntax? Thanks, I'm sorry for the misunderstanding

**Comment by fletcher** [comment]
(Hmmm... Emailed response  seems to have not gone through...)

Options (almost) always go before non-option arguments in command-line programs (at least non-Windows):

    mmd -t html -o newfile.html [myfiles]

**Comment by lucasimp** [comment]
I've tried as you wrote

mmd -t html -o newfile.html myfile.md 

and the result is:
************
MultiMarkdown: option "-t" requires an argument
Try 'multimarkdown --help' for more information.
Error reading file 'html'
MultiMarkdown: option "-o" requires an argument
Try 'multimarkdown --help' for more information.
Error reading file 'newfile.html'
************

But in fact the conversion is made because there is newfile.html in the folder

**Comment by dgreen** [comment]
Do you have a script or alias named mmd that is pre-processing things?  (I do so I thought I would ask if maybe that was doing something with the arguments.)

**Comment by lucasimp** [comment]
Last version of Multimarkdown program for Terminal is 4.5, isn't it?

**Comment by fletcher** [comment]
Latest is 6.2.1 from this week.

**Comment by lucasimp** [comment]
I've downloaded and installed mmd 6.2.1, but 'multimarkdown --version' says 4.5. I don't understand: are they the same thing? Is there difference between multimarkdown command and mmd command? Or perhaps between multimarkdown and multimarkdown 6? Help to me know :)
Thanks a lot

**Comment by fletcher** [comment]
Hmmmm.  I replied but apparently didn't get posted.

If it says 4.5 then you have 4.5 installed.

6.2.1 says 6.2.1. 

`mmd` is just a helper script that sets batch mode `-b` and then runs `multimarkdown`

**Comment by lucasimp** [comment]
'mmd -version' 6.2.1
'multimarkdown -version' 4.5

Where can I download the update of multimarkdown command for Terminal? Not mmd, which I've just updated. Are perhaps the same?

**Comment by fletcher** [comment]
mmd doesn't have a version, it just runs multimarkdown.

You apparently have multiple copies installed in different places.

**Comment by lucasimp** [comment]
Where they could be installed? I've searched with 'whereis' but no answers

**Comment by fletcher** [comment]
Wherever you put them...

;)

I use `where` or `locate`, not `whereis`.  Maybe that would work for you?

**Comment by mn4367** [comment]
`whereis` gave nothing here but `which` did.

**Comment by lucasimp** [comment]
Thanks, I've found with 'which' where is 'multimarkdown' (the first) and I've deleted; it was in /opt/local/bin folder while there is another 'multimarkdown' in /usr/local/bin where is also 'mmd'
