### ISSUE TITLE
Support of Multi-line Metadata Fields such as in Letterhead Support File

### ISSUE THREAD

**Issue by cdhutch** [fletcher/MultiMarkdown-6#86]
I've upgraded to MMDv6 and am updating all of my MMDv5 templates. I've read through [Issue #58](https://github.com/fletcher/MultiMarkdown-6/issues/58) and understand that you've changed the method that you parse whitespace.

I'd like to be able to use your [Letterhead Support File](https://github.com/fletcher/peg-multimarkdown-latex-support), especially the ability to enter a multi-line address in the metadata for subsequent parsing and LaTeX compiling. I've attempted to create a workaround using your new raw syntax to insert multiline latex into the file, but I can't figure out how to squeeze the latex code in before the `\input{mmd6-letterhead-begin}` line without disrupting the metadata parsing.

Would you consider enabling a few additional metadata fields to process raw LaTeX strings, as you have done with `latexauthor` and `latextitle` or providing a more general approach to parsing multiline metadata? If there is a workaround technique to provide this functionality, I would appreciate you sharing that.

Thank you for the great software. It has been a significant part of my workflow for the past few years.

**Comment by fletcher** [comment]
I'll try to think of a more general solution than "whitelisting" a few fields.

**Comment by cdhutch** [comment]
Thank you, Fletcher.

**Comment by fletcher** [comment]
Now you can do something like this:

	Title:	Test Letter  
	Date:	September  1, 2018  
	Recipient:	Mr Smith  
	Recipient address:	123 Main St\
		Some Town, ST 12345  
	Graphic signature:	true  
	Base header level:	2  
	Latex mode:	memoir  
	Latex config:	letterhead  
	Use XeLaTex:	true  


	[%recipientaddress]

	Dear [%Recipient],
