### ISSUE TITLE
`make debug` builds into ${PRODUCT_NAME} subfolder

### ISSUE THREAD

**Issue by DivineDominion** [fletcher/MultiMarkdown-6#91]
The path is, literally:

    build/libMultiMarkdown.framework/Versions/A/include/${PRODUCT_NAME}

![screen shot 2017-10-17 at 10 03 53](https://user-images.githubusercontent.com/59080/31653328-849e3b06-b322-11e7-909b-017f4211d1d7.png)

Changing `CMakeLists.txt` in line 82 from:

	SET_SOURCE_FILES_PROPERTIES(
		${filename}
		PROPERTIES
		MACOSX_PACKAGE_LOCATION
		include/\${PRODUCT_NAME}
	)

To 

	SET_SOURCE_FILES_PROPERTIES(
		${filename}
		PROPERTIES
		MACOSX_PACKAGE_LOCATION
		include/${PRODUCT_NAME}
	)

Gets rid of the weird folder name, but also reveals that when the variable is used at this point, it seems to be empty.

`$(PRODUCT_NAME)` doesn't help, either.

---

```
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A365
---
Xcode 9.0
Build version 9A235
```

**Comment by DivineDominion** [comment]
Is this supposed to be sorted out by `make xcode` only? It replaces some things here, but I still am unable to use the resulting framework because I cannot figure out what the import statement should be, neither in Swift not Objective-C; but that's a different issue, I guess.

**Comment by fletcher** [comment]
Correct -- if you're using Xcode, you need to use `make xcode` or `make xcode-debug`.

**Comment by DivineDominion** [comment]
Ok, thanks. Will take note of all this and hopefully propose README additions that help others to jump on board, too :)
