### ISSUE TITLE
make stops with error "stack.h:68: error: redefinition of typedef ‘stack’"

### ISSUE THREAD

**Issue by halloleo** [fletcher/MultiMarkdown-6#97]
I try to build mmd6 on Centos 6. Cmake28 is installed. I did the follwing:

* Downloaded and unzipped `MultiMarkdown-6-master.zip`
* `cd MultiMarkdown-6-master`
* `make release` (which finished fine, but had at the beginning an error with `git log`)
* `cd build`
* `make`

This gave me the error:
```
Scanning dependencies of target libMultiMarkdown
[  3%] Building C object CMakeFiles/libMultiMarkdown.dir/Sources/libMultiMarkdown/aho-corasick.c.o
[  6%] Building C object CMakeFiles/libMultiMarkdown.dir/Sources/libMultiMarkdown/beamer.c.o
In file included from /installs/MultiMarkdown-6-master/Sources/libMultiMarkdown/mmd.h:61,
                 from /installs/MultiMarkdown-6-master/Sources/libMultiMarkdown/writer.h:64,
                 from /installs/MultiMarkdown-6-master/Sources/libMultiMarkdown/latex.h:62,
                 from /installs/MultiMarkdown-6-master/Sources/libMultiMarkdown/beamer.c:56:
/installs/MultiMarkdown-6-master/Sources/libMultiMarkdown/stack.h:68: error: redefinition of typedef ‘stack’
/installs/MultiMarkdown-6-master/Sources/libMultiMarkdown/include/libMultiMarkdown.h:285: note: previous declaration of ‘stack’ was here
make[2]: *** [CMakeFiles/libMultiMarkdown.dir/Sources/libMultiMarkdown/beamer.c.o] Error 1
make[1]: *** [CMakeFiles/libMultiMarkdown.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by fletcher** [comment]
That doesn't look like a CMake issue, but rather a problem with the compiler/linker/blah-blah toolchain.

I don't use Centos, so have no experience with what it is configured to use.  I can tell you that MMD-6 compiles just fine on multiple other operating systems.

You could try deleting one of those two lines and see if the rest compiles for you then.  Might need to delete it from libMultiMarkdown.h, and then add it back to any other file that seems to need it?

**Comment by halloleo** [comment]
Thank you. 

I tried Mmd-5 instead and was able to compile it - but I had to call the scripts `link_git_modules` and `updates_git_modules`  as mentioned in the doco for 5. 

Do I maybe have to do the same when building Mmd-6?

**Comment by fletcher** [comment]
MMD-6 doesn't have any submodules.  It's self-contained.

**Comment by halloleo** [comment]
But you provide the scripts, eg. [link_git_modules](https://github.com/fletcher/MultiMarkdown-6/blob/master/link_git_modules). What are they for then? 

I ask, because the machine I compile Mmd-6 on, cannot connect to GitHub - therefore I have to do all git magic beforehand, then zip everything up, copy things over and do the make stuff locally.

**Comment by fletcher** [comment]
They're part of my standard c boilerplate project.

**Comment by halloleo** [comment]
Alright, so that can't be the issue then.

So I tried your first suggestion and deleted the culprit line `typedef struct stack stack;`. But it doesn't help: The declaration seems to be needed in `token_pairs.h`...

**Comment by fletcher** [comment]
I pushed a commit to the develop branch for another reason that altered included header files.  You can try that version to see if it works for you.
