### ISSUE TITLE
MMD 6 --process-html equivalent

### ISSUE THREAD

**Issue by feekApp** [fletcher/MultiMarkdown-6#98]
Hi,

What is for MMD6 the `--process-html` equivalent as was used in MMD5 in order to process MD inside HTML code?

**Comment by fletcher** [comment]
There isn't one.  See the Quick Start guide for information about how MMD processes text inside of HTML.

**Comment by alecjacobson** [comment]
I'm looking for the same feature. I couldn't find the part of the https://github.com/fletcher/MultiMarkdown-6/blob/develop/QuickStart/QuickStart.pdf that discusses this.

**Comment by fletcher** [comment]
The documentation has changed over time.

Probably the best place to see how things work is the test suite.  It's heavy on examples, but light on description.

* <https://github.com/fletcher/MultiMarkdown-6/blob/develop/tests/MMD6Tests/HTML%20Blocks.text>
* <https://github.com/fletcher/MultiMarkdown-6/blob/develop/tests/MMD6Tests/HTML%20Comments.text>
* <https://github.com/fletcher/MultiMarkdown-6/blob/develop/tests/MMD6Tests/HTML%20Inline.text>

Another possibility is the newer method for including raw source (for different output formats) -- <https://fletcher.github.io/MultiMarkdown-6/MMD_Users_Guide.html#rawsource>


The basic idea is that if you want HTML to be left alone, then don't include any blank lines within the HTML.  If you want Markdown/MultiMarkdown processed inside the HTML than use blank lines to create separate "paragraphs" that are then processed normally.
